projectcalico/cni-plugin

Makefile, calico_rkt/calico_rkt.py, calico_rkt/constants.py, calico_rkt/ipam.py, calico_rkt/policy_drivers.py, calico_rkt/util.py
Commonize the configure_logging function
=> Move IPAM plugin to CNI repo

samples/README.md, samples/kubernetes/cloud-config/master-config-template.yaml, samples/kubernetes/cloud-config/node-config-template.yaml, samples/kubernetes/common/calico-node.service, samples/kubernetes/master/calico-etcd.manifest, samples/kubernetes/master/dns/skydns.yaml, samples/kubernetes/master/kubelet.service, samples/kubernetes/master/kubernetes-master.manifest, samples/kubernetes/master/network-environment-template, samples/kubernetes/node/kube-proxy.manifest, samples/kubernetes/node/kubelet.service, samples/kubernetes/node/network-environment-template
This configuration will be used by the getting started guides in the main Kubernetes repo.
=> Add sample configuration for Kubernetes.

calico.py, tests/unit/test_cni_plugin.py
Fixes https://github.com/projectcalico/calico-cni/issues/59
=> Remove policy configuration for stale endpoints

Makefile
=> Use latest build container

calico.py, calico_cni/constants.py, tests/unit/test_cni_plugin.py
=> Allow hostname to be configured

samples/kubernetes/cloud-config/master-config-template.yaml
Fixes https://github.com/projectcalico/calico-containers/issues/919
=> Fix sed command in master-config-template.yaml

Dockerfile, Makefile, README.md
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>
=> Add dockerfile for a "calicokube"

calico.go, utils/types.go
Reopening From [old PR](https://github.com/tomdee/calico-cni/pull/1) now that go-code has moved from tom's fork to upstream master.
@tomdee - since @caseydavenport has given a review of the old one, can you give the final OK?
=> Add CNI Argument parsing of mesos-labels.

ipam/calico-ipam.go
=> Fix IPAM handles

calico.go, k8s/k8s.go, utils/utils.go
=> Release IP addresses on failure.

Makefile, README.md
=> Add basic release process

Dockerfile, Makefile
...that can be build just using docker
=> Add a minimal build file for the calico/cni container

Dockerfile.build, calico_cni_test.go, glide.lock, test_utils/utils.go
This also updates the netlink version, which requires some small updates
to the tests
=> Update to latest libcalico

Makefile, k8s/k8s.go
=> Support K8s pods that don't have labels

Dockerfile, Makefile
=> Pass through version into build container

Makefile, glide.lock, glide.yaml, utils/network.go
Fetch the correct IPv6 address to use as next hop
=> Fix IPv6 support

.dockerignore, Dockerfile
=> Add CNI install script to docker image

glide.lock, glide.yaml
Also, pin runc to avoid incompatibility between it and kubernetes
=> Update libcalico-go to latest

configuration.md
=> Add API resource details

k8s-install/scripts/install-cni.sh
For self-hosted access to TLS enabled etcd clusters.
=> Support templating the etcd TLS assets in the calico/cni container

Makefile
Run 'vendor' part inside Docker container in
case of containerized build.
Change-Id: I6564ef4a7debb2735e8c1c847161442287a4b8d4
=> Make fully containerized build

Makefile
We need to have an ability to pass custom URL for calicoctl binray
The default value is not changed
=> Allow to parameterize calicoctl binary URL

glide.lock, glide.yaml
Fixes issue [#1295](https://github.com/projectcalico/calico-containers/issues/1295)
Related libcalico-go commit: https://github.com/projectcalico/libcalico-go/commit/7fe78bddb69c99b5838d37307e3737c9b15d0f7d
=> Pin libcalico-go tag for dup IP bugfix

utils/utils.go
Don't set up glog anymore - was used by libcalico
=> Clean up logging config

ipam/calico-ipam.go
=> CNI calico-ipam version flag

k8s-install/scripts/install-cni.sh
support kubelet arg `--hostname-override`
=> add KUBERNETES_NODE_NAME param

Makefile
Now it's possible to run static checks (Golang code)
inside container, so all make targets for CI can
be executed within Docker.
Change-Id: I9f8ac37909db712ee97c914b7766336889dfb875
=> Run all CI targets inside Docker containers

Makefile
By default (HTTP) Fail silently (no output at all) on server errors.
This is mostly done to better enable scripts etc to better
deal with failed attempts.
So we must fail if some resources are unavailable
=> Return error on any issues with curl

Makefile
We need to create directories for several targets
=> Ensure directories exist before making any manipulations

Makefile, calico_cni_ipam_test.go, calico_cni_k8s_test.go, test_utils/utils.go
=> Add k8s test

Makefile, k8s-install/scripts/install-cni.sh
Added target for fetching CNI binaries, and marker to avoid re-download when they exist.
=> Smarter fetching of 3rd party CNI binaries

calico.go
=> Bugfix: IP leak. Clean up IP address with host-local IPAM

k8s-install/scripts/install-cni.sh
#247 added a default CNI config to the install container.  However, the shell script which decided whether or not to override that didn't properly handle the CNI_NETWORK_CONFIG env var being unset. 
This PR allows for CNI_NETWORK_CONFIG to be unset, defaulting to the config in the container.
=> Fix up install script missing env var

calico_cni_ipam_test.go, calico_cni_k8s_test.go, ipam/calico-ipam.go, k8s/k8s.go, test_utils/utils.go, utils/types.go, utils/utils.go
Pulling @duglin's PR #223 and applying test fixes + review changes + some more tests
Fixes #213
=> Add support for the new IPv4Pools and IPv6Pools properties on AutoAssign 

calico_cni_k8s_test.go, ipam/calico-ipam.go, k8s/k8s.go
Second annotation for https://github.com/projectcalico/cni-plugin/issues/258
Example annotation:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: my-nginx-mixed
spec:
replicas: 1
template:
metadata:
labels:
run: my-nginx-mixed
annotations:
"cni.projectcalico.org/ipAddrs": "[\"192.168.0.65\", \"2001:db8::65\"]"
spec:
containers:
- name: my-nginx-mixed
image: nginx
ports:
- containerPort: 80
```
```bash
...
4: eth0@if28: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
link/ether c6:3b:c3:8e:a3:17 brd ff:ff:ff:ff:ff:ff
inet 192.168.0.65/32 scope global eth0
valid_lft forever preferred_lft forever
inet6 2001:db8::65/128 scope global
valid_lft forever preferred_lft forever
inet6 fe80::c43b:c3ff:fe8e:a317/64 scope link
valid_lft forever …
```
=> Support ipAddrs annotation to assign a specific IP to a pod through IPAM

calico_cni_k8s_test.go, calico_cni_test.go, test_utils/utils.go
=> add tests for host-local IPAM IP leak bugfix

utils/network.go
=> IPv6 setup can't get the IP and won't add the correct default route

Makefile, calico.go, calico_cni_test.go, k8s/k8s.go, utils/types.go
=> Hostname to nodename

README.md
=> Readme.md: Add note about building outside of containers

calico_cni_k8s_test.go, calico_cni_test.go, test_utils/utils.go, utils/network.go
=> Fixed #275: Clean up if hostVeth exists

calico_cni_k8s_test.go, calico_cni_test.go
Check CreateHostVeth() return value in tests.
Fixes #307
=> Fix gometalinter warnings

k8s-install/scripts/install-cni.sh
=> Change tmp cfg file path to be absolute

calico.go, calico_cni_k8s_test.go, calico_cni_test.go, glide.lock, glide.yaml, k8s/k8s.go, utils/utils.go
Fixes https://github.com/projectcalico/cni-plugin/issues/310
=> Check ContainerID before Deleting a pod

calico.go, calico_cni_k8s_test.go, calico_cni_test.go, test_utils/utils.go, utils/utils.go
fixes #317 
fixes #318 
also getting rid of dot imports slowly
=> bugfix: parse IP, pass ip version in result + tests

calico.go, k8s/k8s.go, utils/utils.go
A version of #326 without the hokey tests which aren't working yet.
=> Release IPs on bad IPAM result

Makefile
Make the portmap plugin executable
=> Make portmap plugin executable

calico_cni_ipam_test.go, calico_cni_k8s_test.go, glide.lock, glide.yaml, k8s/k8s.go, test_utils/utils.go
- Update pins in glide.yaml to track latest minor release of each dependency.
- Pin client-go to known working commit from libcalico-go
=> Update glide.yaml pins

calico.go, calico_cni_k8s_test.go, calico_cni_test.go, glide.lock, glide.yaml, ipam/calico-ipam.go, test_utils/utils.go
Added a new logging format to follow the same structure as logs in Felix to provide more information in a more easily understood way
Requires https://github.com/projectcalico/libcalico-go/pull/474
Fixes https://github.com/projectcalico/cni-plugin/issues/236
- Ran the unit tests and verified the logs are formatted appropriately
=> Added a more consistent logging format

glide.lock, glide.yaml
Part of a series of PRs to consistently pin logrus across Calico repos.
```release-note
None required
```
=> Update glide.yaml to pin logrus

calico_cni_k8s_test.go
In current master, a successful test run through with no errors will spit out random log messages from various tests.
This PR logs to the ginkgowriter stream which hides output unless the test fails.
```release-note
None required
```
=> Log tests to ginkgowriter

calico_cni_k8s_test.go, test_utils/utils.go
Use `subprocess.Env` instead of `bash -c 'ENV ...'`
:taco: 
```release-note
None required
```
=> Use Subprocess.env instead of injecting env into bash

README.md
Signed-off-by: Hui Kang <kangh@us.ibm.com>
```release-note
None required
```
=> README: fix and update links

k8s-install/scripts/install-cni.sh
`install-cni.sh` doesn't overwrites binaries by default. That creates troubles during upgrade, because I had to remove stuff in `/opt/cni/bin` and then restart a calico/canal pod. Or just put binaries by hand.
Thes PR adds a new environment variable `UPDATE_CNI_BINARIES` which is `true` by default. If `UPDATE_CNI_BINARIES` is `true`, CNI binaries would be overwritten. If it's `false`, existing binaries would stay, like it was before the patch.
```release-note
install-cni.sh will now replace system CNI binaries, use UPDATE_CNI_BINARIES=false to restore old behavior 
```
=> Overwrite CNI binaries by default

k8s-install/scripts/install-cni.sh
Fixes #360 
It looks like this with this PR:
```
Wrote CNI config: {
"name": "k8s-pod-network",
"cniVersion": "0.1.0",
"type": "calico",
"etcd_endpoints": "http://10.96.232.136:6666",
"log_level": "info",
"mtu": 1500,
"ipam": {
"type": "calico-ipam"
},
"policy": {
"type": "k8s",
"k8s_api_root": "https://10.96.0.1:443",
"k8s_auth_token": "*****"
},
"kubernetes": {
"kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
}
}
```
```release-note
NONE
```
=> Mask k8s auth token from install-cni scrip logs.

calico.go, k8s/k8s.go
Fixes #377 
```release-note
Bugfix: container deletion failure due to CNI panic
```
=> bugfix: fail to delete pods due to CNI panic

glide.lock, glide.yaml
bump libcalico-go to v1.7.1. All tests pass.
```release-note
None required
```
=> bump libcalico-go to v1.7.1

k8s-install/scripts/install_cni_test.go
Fixes #393 
Currently, the way the felix.containers works is when you run a container it waits to see it come online by issuing some checks (`docker ps`, and `docker inspect`) which works fine for long running containers. On short lived containers, such as the `cleanup()` call, the container might sometimes exit before it has been verified to be running.
I've changed the `cleanup()` call to use an `exec.Command()` to reach out to docker instead of using the felix.containers package to get around this.
```release-note
None required
```
=> Running install_cni_test.cleanup() with exec.Command()

Makefile, calico.go, calico_cni_ipam_test.go, calico_cni_k8s_test.go, calico_cni_test.go, glide.lock, glide.yaml, ipam/calico-ipam.go, k8s/k8s.go, testutils/utils.go, types/types.go, utils/network.go, utils/utils.go
Update CNI to use the V2 API
I've also taken this opportunity to refactor the code a little bit.
```release-note
None Required
```
=>  Update CNI to use the V2 API

.gitignore, Makefile, calico.go, calico_cni_k8s_test.go, calico_cni_test.go, glide.lock, glide.yaml, k8s-install/scripts/expected_10-calico.conf, k8s-install/scripts/install-cni.sh, k8s-install/scripts/install_cni_test.go, k8s-install/scripts/scripts_suite_test.go, k8s/k8s.go, testutils/utils.go, utils/network.go, utils/utils.go
```release-note
None required
```
=> Merging master into v3.0-integration

calico.go, calico_cni_k8s_test.go, calico_cni_test.go, glide.lock, glide.yaml, k8s/k8s.go
```release-note
None required
```
=> Update for new label format and new profile naming format

Makefile
```release-note
None required
```
=> Make release instructions clear about latest images

calico_cni_k8s_test.go, calico_cni_test.go, glide.lock, glide.yaml, k8s/k8s.go, testutils/utils.go
Fixes https://github.com/projectcalico/cni-plugin/issues/410
Need to rev in libcalico once https://github.com/projectcalico/libcalico-go/pull/665 is merged
```release-note
None required
```
=> Use WEP name and namespace to uniquely generate the vethname

glide.lock, glide.yaml, k8s-install/scripts/install_cni_test.go
Revving libcalico-go and fixing the tests for `install-cni.sh` as there were some changes to the containers package that are causing them to fail, so I've resorted to just calling the docker daemon directly from the tests as they are pretty simple anyway.
```release-note
None required
```
=> Revving libcalico

calico.go, calico_cni_k8s_test.go, calico_cni_test.go, glide.lock, glide.yaml
Continuation of #421 
Rev libcalico-go to master and fix up tests.
```release-note
None required
```
=> Rev libcalico go to master

Makefile, glide.lock, glide.yaml
```release-note
None required
```
=> Rev libcalico-go to v1.7.2 and pin go-build to v0.8 (golang 1.8.5).

glide.lock, glide.yaml
bump libcalico-go to v1.7.3
```release-note
None required
```
=> bump libcalico-go to v1.7.3

calico_cni_test.go, utils/network.go
=> Generate MAC addr from container ID

calico.go, calico_cni_test.go, testutils/utils.go
```release-note
None required
```
=> If ready flag is not true then do not proccess ADD or DEL

calico_cni_k8s_test.go, calico_cni_test.go, glide.lock, glide.yaml, utils/utils.go
```release-note
None required
```
=> Fix detection of hostname to use lowercase

calico_cni_ipam_test.go, calico_cni_k8s_test.go, calico_cni_test.go, ipam/calico-ipam.go, utils/utils.go
This PR changes the IPAM handle to be a combination of the network name and the container ID.
```release-note
None required
```
=> Forward porting IPAM handle change to master

.dockerignore, Dockerfile-s390x, Makefile
=> Added support for s390x

.dockerignore, Dockerfile-s390x, Makefile
Backport s390x support.
(cherry picked from commit 9ee6b49f0353308ef7548074015138a0ec5aa0fd)
```release-note
Backport s390x build support
```
=> [v3.0] Backport s390x build support

calico.go, calico_cni_test.go, types/types.go, utils/network.go
#501 
```release-note
Add support for configuring container IP forwarding via the CNI configuration file.
```
=> [v3.0] cherry pick 501

calico.go, calico_cni_test.go, types/types.go, utils/network.go
#501 
```release-note
Add support for configuring container IP forwarding via the CNI configuration file.
```
=> [v3.1] cherry pick 501

testutils/utils.go
```release-note
None required
```
=> Remove CreateContainerNamespaceWithCid

Makefile, RELEASING.md, k8s-install/scripts/install_cni_test.go
Matches the format introduced here: https://github.com/projectcalico/kube-controllers/pull/246
```release-note
None required
```
=> Update release targets

Makefile, RELEASING.md, k8s-install/scripts/install_cni_test.go
#511
```release-note
None required
```
=> [release-v3.1] cherry-pick: Update release targets

k8s-install/scripts/install-cni.sh
Cherry-picking #526 and #527 
```release-note
Fix etcd cert file existence check in calico/cni (@bjhaid)
```
```release-note
When ran as a pod CNI will be configured with K8s CA for tls verification.
```
=> Cherry-pick 526 and 527 into v3.1 release branch

calico_cni_k8s_test.go, k8s/k8s.go
Fixes https://github.com/projectcalico/cni-plugin/issues/520 by always assigning a new IP address to a pod when ADD is called.
```release-note
None required
```
=> Always allocate a new IP on k8sCmdAdd

Makefile
Will make publishing updates to GKE easier. 
```release-note
None required
```
=> Add GCR images to standard tag/push targets

Makefile
```release-note
None required
```
=> Add GCR image tagging

calico_cni_k8s_test.go, k8s/k8s.go
#529 
```release-note
Fix a bug in the CNI plugin where IP allocations were not properly updated on container restart
```
=> [release-v3.0] cherry-pick: Always allocate a new IP on k8sCmdAdd

calico_cni_k8s_test.go, k8s/k8s.go
#529 
```release-note
Fix a bug in the CNI plugin where IP allocations were not properly updated on container restart
```
=> [release-v3.1] cherry-pick: Always allocate a new IP on k8sCmdAdd

calico_cni_k8s_test.go, glide.lock, glide.yaml, k8s/k8s.go
Keep track of the K8s metadata `GenerateName`
=> Store GenerateName metadata.

.dockerignore, .gitignore, Dockerfile.amd64, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x, Makefile, git-hooks/pre-commit, install-git-hooks, testutils/utils.go
move from dist to bin
Remove old and unused targets
=> Clean up Makefile

utils/network.go
The notice was copied from other files in the commit
which introduced this file. [1]
Background: I have a copy of this file in my project, [2]
which uses check-copyrights.sh style checking to ensure
every files have a copyright notice.
[1] 218378bc7e484fe70c72d23dd6c9f1a9a612ec64
[2] https://github.com/midonet/midonet-kubernetes
```release-note
None required
```
=> Add a copyright notice to network.go

Makefile
Parameterize the build image docker hub repo name
Signed-off-by: jose-bigio <jose.bigio@docker.com>
```release-note
None required
```
=> Parameterize the build image docker hub repo name

README.md
update make build in native
change 'make binary' to 'make build'
- [1] Documentation
```release-note
None required
```
=> update make native build

Dockerfile
Fixes #555.
```release-note
NONE
```
=> Remove `VOLUME /opt/cni` which is not necessary now.

glide.lock, glide.yaml
Update libcalico pin and clean glide
=> Update libcalico pin and clean glide

Makefile
Cherry pick to fix https://semaphoreci.com/calico/cni-plugin/branches/release-v3-1/builds/65
=> Makefile: Only push images to GCR on release

Makefile, glide.lock, glide.yaml
Glide needs to be run twice (https://github.com/Masterminds/glide/issues/1003)
Filter out the known warning during `glide up`
=> Makefile: Add update-libcalico target

calico_cni_k8s_test.go, utils/network.go
- Move the per-IP -version set-up (sysctls and routes) out of the loop over IPs.
- Simplify the loop over IPs (since there's no reliance on IP version in there any more)
- Add asserts to existing tests to verify number of IPs assigned.
```release-note
None required
```
=> Fix that CNI plugin allowed at most one IPv4 and one IPv6 address.

calico_cni_k8s_test.go, utils/network.go
Backport of #573 
```release-note
None required
```
=> [v3.2] Fix that CNI plugin allowed at most one IPv4 and one IPv6 address.

Makefile
```release-note
None required
```
=> Release all arch

Makefile
https://github.com/projectcalico/cni-plugin/pull/576
```release-note
None required
```
=> release-v3.2: cherry-pick release fixes

Makefile
```release-note
None required
```
=> Fixup GCR names

Makefile
```release-note
None required
```
=> Fix projectcalico.org -> projectcalico-org

calico_cni_k8s_test.go, k8s/k8s.go
Reimplementing #529 on the v2.6 branch.
- Always allocate a new IP address for pods, even when the wep exists.
- Always deallocate IP addresses for a given container ID, even if the wep doesn't exist or doesn't match.
```release-note
Fix a bug in the CNI plugin where IP allocations were not properly updated on container restart
```
=> Always allocate a new IP

Makefile
We were missing this on v2.6 - this is just the bare minimum to get things working. I didn't port all of the image tagging machinery from v3 since there is a large diff. 
```release-note
None required
```
=> Add simple cd target to Makefile

Makefile
```release-note
None required
```
=> Makefile: Bump K8s to v1.11.3

calico_cni_k8s_test.go, k8s/k8s.go, types/types.go
One way of fixing https://github.com/projectcalico/calico/issues/2172
```release-note
None required
```
=> Add option to program default routes

calico.go, k8s/k8s.go
Fixes https://github.com/projectcalico/cni-plugin/issues/593
```release-note
None required
```
=> Include created interface in CNI result

calico.go, calico_cni_k8s_test.go, contrib/test_scripts/netconf/calico-go-with-host-local.json, contrib/test_scripts/util.py, k8s/k8s.go, types/types.go, utils/utils.go
https://github.com/projectcalico/cni-plugin/pull/581
#592 
#594 
```release-note
Shut down CNI plugin if execution takes over 30 seconds (@tomdee)
```
```release-note
Include created interface in CNI result
```
```release-note
Add CNI option to always install default routes
```
=> cherry-pick various fixes to release-v3.2

Makefile
https://github.com/projectcalico/cni-plugin/pull/600/commits
```release-note
None required
```
=> cherry-pick: Fix release picks

glide.lock, glide.yaml
```release-note
None required
```
=> Update libcalico to pick up blockSize changes

calico_cni_k8s_test.go
Removes some unnecessary Contexts and organizes similar tests near each other.  Combines some shared code into BeforeEach / AfterEach blocks. 
```release-note
None required
```
=> Quick round of test cleanup

Makefile
@fasaxc WDYT? Until now, we've only supported this on master.
Adding this means we should be able to have Semaphore automtaically update libcalico for us on all release branches.
```release-note
None required
```
=> Support update-libcalico on branches other than master

Makefile, calico.go, calico_cni_k8s_test.go, glide.lock, glide.yaml, ipam/calico-ipam.go, testutils/utils.go, utils/network_linux.go, utils/utils.go
Pick up API changes on way to v0.4 support.
Bit of refactoring to make it easier to support other platforms in future.
```release-note
None required
```
=> Rev CNI dependencies to recent master.

k8s/k8s.go, utils/utils.go
```release-note
None required
```
=> Stop logging client config

internal/pkg/azure/azure_suite_test.go, internal/pkg/azure/azure_test.go, internal/pkg/azure/endpoint.go, internal/pkg/azure/network.go
```release-note
None required
```
=> Add basic tests for azure package

glide.lock
```release-note
None required
```
=> Update libcalico-go to 3655574dc6162df9974bbdebab072b5ee104b554

calico.go
```release-note
None required
```
=> Don't log cni net config

k8s/k8s.go, utils/utils.go
Cherry pick PR #628 
```release-note
None required
```
=> [release-v2.6] cherry-pick: Stop logging client config and env vars

k8s/k8s.go, utils/utils.go
Cherry picks PR #628 
```release-note
None required
```
=> [release-v3.2] cherry-pick: Stop logging client config and env vars

k8s/k8s.go, utils/utils.go
Cherry picks PR #628 
```release-note
None required
```
=> [release-v3.3] cherry-pick: Stop logging client config and env vars

calico.go
Cherry picks #635 
```release-note
None required
```
=> [release-v2.6] cherry-pick: Don't log cni net config

calico.go
Cherry picks #635 
```release-note
None required
```
=> [release-v3.2] cherry-pick: Don't log cni net config

calico.go
Cherry picks #635 
```release-note
None required
```
=> [release-v3.3] cherry-pick: Don't log cni net config

k8s/k8s.go, utils/utils.go
```release-note
None required
```
=> Remove logging of stdin data

k8s/k8s.go, utils/utils.go
Port of https://github.com/projectcalico/cni-plugin/pull/643
```release-note
None required
```
=> [release-v2.6] Remove stdin data logging

k8s/k8s.go, utils/utils.go
https://github.com/projectcalico/cni-plugin/pull/643
```release-note
None required
```
=> [release-v3.2] Remove stdindata logs

k8s/k8s.go, utils/utils.go
https://github.com/projectcalico/cni-plugin/pull/643
```release-note
None required
```
=> [release-v3.3] Remove stdindata logs

calico.go, k8s/k8s.go, utils/utils.go
https://github.com/projectcalico/cni-plugin/pull/643/
https://github.com/projectcalico/cni-plugin/pull/635/
https://github.com/projectcalico/cni-plugin/pull/628/
```release-note
None required
```
=> [release-v3.1] Stop logging client config

calico.go, k8s/k8s.go, utils/utils.go
```release-note
None required
```
=> [release-v3.0] Stop logging client config

calico_cni_k8s_test.go, calico_cni_test.go, utils/utils.go
This is a simple testing change that specifically checks custom MTU values. It was created in an attempt to replicate https://github.com/projectcalico/calico/issues/2200
=> Adding MTU tests in reference to projectcalico/calico #2200

Makefile
```release-note
None required
```
=> Fix some release stuff on 3.1

Makefile
Trying out `ghr` for building a github release in an automated way.
For more info: https://github.com/tcnksm/ghr/tree/develop
```release-note
None required
```
=> Try using ghr for github release publishing

Makefile
```release-note
None required
```
=> v3.2 Backport GHR

internal/pkg/utils/network_linux.go
fix #1937
```release-note
None
```
=> set proxy_delay before set proxy_arp to avoid kernel panic

calico.go, contrib/test_scripts/netconf/calico-go-with-host-local.json, contrib/test_scripts/util.py, k8s/k8s.go, utils/utils.go
Backport #599, including fix for hang on some kernel versions.
Skipped the fix that added a new config parameter to always program default routes since that was a fix to a feature that was added in v3.2.
```release-note
None required
```
=> Backport various fixes

glide.lock, glide.yaml, pkg/ipamplugin/ipam_plugin.go
Stores pod name/namespace as well as the node of allocation.
Requires this guy: https://github.com/projectcalico/libcalico-go/pull/1035
```release-note
None required
```
=> Store additional attributes with IP allocations

pkg/upgrade/migrate.go
- Handle not exist errors more gracefully
- Add extra unlocking
- Fix IPIP tunnel attributes 
```release-note
None required
```
=> Tweaks to IPAM upgrade

pkg/upgrade/migrate.go
```release-note
None required
```
=> Set handle on IPIP tunnel addr during migration

Makefile
```release-note
None required
```
=> backport release changes to v3.1

Makefile
```release-note
None required
```
=> backport release changes to v3.0

Makefile
```release-note
None required
```
=> Fix GCR images for release

Makefile
```release-note
None required
```
=> Remove duplicate release target

Makefile
```release-note
None required
```
=> Fix GIT_VERSION missing in Makefile v3.0

Makefile
```release-note
None required
```
=> Fix creation of bin/github dir

Makefile
```release-note
None required
```
=> Fix release publishing v3.1

Dockerfile, Dockerfile.amd64, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x, k8s-install/scripts/install-cni.sh, k8s-install/scripts/install_cni_test.go
Modifying Dockerfiles to use debian instead of alpine as base.
- No new tests, just fixed issues with regression tests
```release-note
None required
```
=> Modifying Dockerfiles to use debian instead of alpine as base

pkg/upgrade/migrate.go
```release-note
None required
```
=> Fix nil nodespec in migration code

pkg/upgrade/migrate.go
Cherry pick of #710 on release-v3.6.
#710: Fix nil nodespec in migration code
```release-note
Fix upgrade initialization error when setting IPIP tunnel address
```
=> Automated cherry pick of #710: Fix nil nodespec in migration code

Makefile
Rev CNI version to 0.7.5
```release-note
None required
```
=> Rev CNI version to 0.7.5

Makefile
Cherry pick of #713 on release-v3.5.
#713: Rev CNI version to 0.7.5
```release-note
Update to CNI plugins v0.7.5
```
=> Automated cherry pick of #713: Rev CNI version to 0.7.5

internal/pkg/testutils/utils.go, internal/pkg/testutils/utils_linux.go, internal/pkg/utils/network_linux.go, internal/pkg/utils/utils.go, pkg/types/types.go
```release-note
None required
```
=> Split out OS-specific function.

pkg/upgrade/migrate.go
```release-note
None required
```
=> Add missing continue in retry loop.

internal/pkg/utils/network_linux.go
A fix for https://github.com/projectcalico/calico/issues/2553
Detailed info what is happening is in the link, this is probably the easiest fix of all. I've been testing the code (or at least its calico 3.3 branch) for a while now and it seems to be working great (actually triggered several retries). 
```
Apr 24 09:10:17 <hostname redacted> kubelet[13796]: 2019-04-24 09:10:17.326 [INFO][19173] network.go 212: No IPv6 set on interface, retrying.. ContainerID="f5276c4c91358bfa76ee56c654e5ce83e3aca22dccec5104f0c581632a87510a" Namespace="default" Pod="test-ipv6-fvirtbase-1556089800-lggbv" WorkloadEndpoint="<hostname redacted>-k8s-test--ipv6--fvirtbase--1556089800--lggbv-eth0"
```
The bug was there always, just a recent change either in kubelet or something has made the logic faster and …
=> Retry on IPv6 listing

Makefile
```release-note
None required
```
=> Adding -C option to curl to ensure download of cni-plugins wont fail

internal/pkg/utils/network_linux.go
Cherry pick of #730 on release-v3.6.
#730: Retry on IPv6 listing
```release-note
Retry on error when configuring IPv6 interfaces (@CallMeFoxie)
```
=> Automated cherry pick of #730: Retry on IPv6 listing

pkg/upgrade/migrate.go
Fixes https://github.com/projectcalico/calico/issues/2516
```release-note
None required
```
=> Handle nil pointers better in migration script

pkg/upgrade/migrate.go
Cherry pick of #726 on release-v3.7.
#726: Handle nil pointers better in migration script
```release-note
Fix panic in CNI plugin migration script
```
=> Automated cherry pick of #726: Handle nil pointers better in migration script

pkg/k8s/k8s.go
Bug fix: Changed ordering of events so that IP is released after the interface is removed to prevent potential race condition / two interfaces sharing one IP
=> Changed order of releasing IP and removing interface

Dockerfile.amd64
```release-note
None required
```
=> Use debian 10 base image

Dockerfile.amd64
```release-note
Update calico/cni base image to debian 10
```
=> Update base image to debian 10

Makefile, go.mod, hack/check-dirty.sh
```release-note
None required
```
=> Add assertion that CI builds do not result in dirty state

Makefile, go.sum
```release-note
None required
```
=> Assert not dirty when pushing images

Makefile
Similar to flurry of other ordering fixes
=> Move package_name to the top so -w option works in Makefile

Makefile
similar to other fixes for make cleaning
=> remove the whole bin/ directory

go.mod, go.sum, internal/pkg/testutils/utils_linux.go, tests/calico_cni_k8s_test.go
This PR tests the pod patching code change of https://github.com/projectcalico/libcalico-go/pull/1168.
It shouldn't be merged as is: the libcalico-go should be adjusted after the libcalico-go PR has been merged.
=> Test dual stack IP allocation and pod annotation

pkg/ipamplugin/ipam_plugin.go
In larger clusters, IPAM calls might actually come close to the previous limit so increase the timeout considerably.
```release-note
```
=> Increase context timeout to 90s

pkg/ipamplugin/ipam_plugin.go
Cherry-pick #807
```release-note
Timeouts added to Calico CNI calls
```
=> release-v3.10 - Cherry-pick timeouts addition

pkg/ipamplugin/ipam_plugin.go
Cherry-pick #807
```release-note
Timeouts added to Calico CNI calls
```
=> release-v3.9 - Cherry-pick timeouts addition

pkg/ipamplugin/ipam_plugin.go
Cherry-pick #807
```release-note
Timeouts added to Calico CNI calls
```
=> release-v3.8 - Cherry-pick timeouts addition

pkg/upgrade/migrate.go
Cherry-pick of https://github.com/projectcalico/cni-plugin/pull/824
```release-note
None required
```
=> release-v3.11 - Cherry-pick Fix containerID read during IPAM migration

pkg/upgrade/migrate.go
Cherry-pick of https://github.com/projectcalico/cni-plugin/pull/824
```release-note
None required
```
=> release-v3.8 - Cherry-pick Fix containerID read during IPAM migration

pkg/upgrade/migrate.go
Cherry-pick of https://github.com/projectcalico/cni-plugin/pull/824
```release-note
None required
```
=> release-v3.9 - Cherry-pick Fix containerID read during IPAM migration

pkg/upgrade/migrate.go
Cherry-pick of https://github.com/projectcalico/cni-plugin/pull/824
```release-note
None required
```
=> release-v3.10 - Cherry-pick Fix containerID read during IPAM migration

Makefile
Fix release image push
```release-note
None required
```
=> Cherry-picck Merge pull request #833 from lmm/lmm-fix-image-push

k8s-install/scripts/install-cni.sh, k8s-install/scripts/install_cni_test.go, tests/calico_cni_k8s_test.go, tests/calico_cni_test.go
Fixes #835 - which will make the install script actually wait for the data store connection.
Also fixes up tests so that we are actually testing this functionality.
```release-note
None required
```
=> Install cni bash compat

tests/calico_cni_k8s_test.go
Signed-off-by: Spike Curtis <spike@tigera.io>
This relates to https://tigera.atlassian.net/browse/CNX-11408 on the private branch of this repo, but we should merge it here first to ensure that OSS sees the benefit, and to make later merges less painful.
```release-note
None required
```
=> ensure kube can get pods after create

k8s-install/scripts/install-cni.sh
fix bug introduced by a6656bd21dd62e21c1c59396c40d3fa35e2f7f2f
```release-note
None required
```
=> fix shell stderr redirect error

Dockerfile.amd64
Cherry pick of #848: Add `hostname` to the image and pin image on release-v3.11.
=> Automated cherry pick of #848: Add `hostname` to the image and pin image

README.md, licenses/Apache-2.0, licenses/BSD, licenses/ISC, licenses/MIT, licenses/Mozilla-public
```release-note
None required
```
=> Include more license information

go.mod, go.sum
```release-note
None required
```
=> Update of libcalico-go pins

.dockerignore, Dockerfile.amd64, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x, README.md, licenses/Apache-2.0, licenses/BSD, licenses/GPLv2, licenses/ISC, licenses/MIT, licenses/Mozilla-public
```release-note
None required
```
=> Add licenses to built image

.dockerignore, Dockerfile.amd64, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x, README.md, licenses/Apache-2.0, licenses/BSD, licenses/GPLv2, licenses/ISC, licenses/MIT, licenses/Mozilla-public
Cherry pick of #870 on release-v3.14.
#870: Add licenses to built image
=> Automated cherry pick of #870: Add licenses to built image

pkg/dataplane/linux/linux_dataplane.go
```release-note
None required
```
=> Disable accept_ra for the host veth

internal/pkg/utils/network_linux.go
Cherry pick of #879: Disable accept_ra for the host veth, on .
=> Automated cherry pick of #879: Disable accept_ra for the host veth

internal/pkg/utils/network_linux.go
Cherry pick of #884: Disable accept_ra for the host veth, on .
=> Automated cherry pick of #884: Disable accept_ra for the host veth

internal/pkg/utils/network_linux.go
Cherry pick of #883: Disable accept_ra for the host veth, on .
=> Automated cherry pick of #883: Disable accept_ra for the host veth

internal/pkg/utils/network_linux.go
Cherry pick of #882: Disable accept_ra for the host veth, on .
=> Automated cherry pick of #882: Disable accept_ra for the host veth

internal/pkg/utils/network_linux.go
Cherry pick of #881: Disable accept_ra for the host veth, on .
=> Automated cherry pick of #881: Disable accept_ra for the host veth

internal/pkg/utils/network_linux.go
Cherry pick of #880: Disable accept_ra for the host veth, on .
=> Automated cherry pick of #880: Disable accept_ra for the host veth

pkg/dataplane/linux/linux_dataplane.go
Cherry pick of #878: Disable accept_ra for the host veth, on .
=> Automated cherry pick of #878: Disable accept_ra for the host veth

Makefile
```release-note
Upstream CNI plugins updated to v0.8.6
```
=> Update CNI plugins version

.gitignore, Makefile, go.mod, go.sum, tests/calico_cni_k8s_test.go
```release-note
None required
```
=> Update libcalico-go for new CRDs

internal/pkg/azure/azure_suite_test.go, internal/pkg/testutils/utils.go, internal/pkg/testutils/utils_linux.go, internal/pkg/utils/utils.go, internal/pkg/utils/utils_test.go, pkg/dataplane/dataplane.go, pkg/dataplane/grpc/grpc_dataplane.go, pkg/dataplane/grpc/proto/cnibackend.pb.go, pkg/dataplane/grpc/test_server.go, pkg/dataplane/linux/linux_dataplane.go, pkg/ipamplugin/ipam_plugin.go, pkg/k8s/k8s.go, pkg/plugin/plugin.go, tests/calico_cni_ipam_test.go, tests/calico_cni_k8s_test.go, tests/calico_cni_test.go
Noticed that running `make fix` for my recent PR changed a lot of files so I split out a run of `make fix` into this PR.
```release-note
None required
```
=> Run current version of goimports.

Dockerfile.amd64
```release-note
None required
```
=> Fix vulnerabilities

pkg/plugin/plugin.go
```release-note
Handle panics in the CNI plugin more gracefully
```
=> Handle panics in the CNI plugin gracefully

Dockerfile.amd64, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x
=> Reintroduce CMD in Dockerfile

pkg/install/install.go
This is required so that the new script works with openshift. Openshift installs CNI and other configuration in an alternate path.
```release-note
None required
```
=> Use relative path

Makefile
```release-note
None required
```
=> Update gobuild v0.45

go.mod, go.sum, pkg/k8s/k8s.go
Make sure that we delete the correct resource when cleaning up WEPs.
```release-note
None required
```
=> Fill in resource version and UID when doing a delete.

.semaphore/run-win-fv.sh, .semaphore/semaphore.yml, Makefile
This is to avoid having Windows binaries into cni docker image.
```release-note
None required
```
=> Use bin/windows as windows binary directory

go.mod, go.sum, pkg/k8s/k8s.go
```release-note
None required
```
=> [v3.16] Backport bpf fixes

pkg/plugin/plugin.go
Handle panics in the CNI plugin gracefully
```release-note
None required
```
=> Cherry-pick Merge pull request #913 from caseydavenport/casey-panic-recovery

Makefile
```release-note
None required
```
=> Fix that CNI plugin itself was only being included if make ut was run

go.mod, go.sum
```release-note
None required
```
=> [release-v3.16] Update pins

Makefile
```release-note
None required
```
=> Revert broken artifact naming

pkg/install/install.go, pkg/install/install_test.go
We were comparing against the container filesystem, when we should have
been comparing against the host filesystem.
```release-note
Fix population of etcd certificates in CNI config
```
=> Fix installation of etcd secrets into config file

.semaphore/semaphore.yml, .semaphore/update_pins.yml, Makefile
```release-note
None required
```
=> Add pin update pipeline

pkg/install/install.go, pkg/install/install_test.go
```release-note
None required
```
=> Fix issue moving files into place during install

pkg/install/install.go, pkg/install/install_test.go
Cherry pick of #966 on release-v3.16.
#966: Fix issue moving files into place during install
```release-note
Fix that installing CNI plugin would fail if binaries were in use
```
=> Automated cherry pick of #966: Fix issue moving files into place during install

.semaphore/semaphore.yml, Makefile
Also make sure that pin updates are being cascaded (previously they weren't).
```release-note
None required
```
=> Fix release branch pin update regex (add ^ to start)

.semaphore/semaphore.yml, Makefile
```release-note
None required
```
=> Finish Semaphore V2 migration

.semaphore/semaphore.yml
Accidentally used the wrong credentials to push the images.
```release-note
None required
```
=> Use quay credentials to push images

pkg/install/install.go
Cherry-pick of https://github.com/projectcalico/cni-plugin/pull/979
```release-note
Fix a bug that made the UPDATE_CNI_BINARIES environment variable not behave as expected.
```
=> Fix update CNI binary logic

Makefile
Cherry pick of #991 on release-v3.17.
#991: Fix make cd target to use correct tag for docker images
=> Automated cherry pick of #991: Fix make cd target to use correct tag for docker images

.semaphore/semaphore.yml
```release-note
None required
```
=> Update semv2 to run full CI

internal/pkg/utils/utils.go
Warning level doesn't give enough context to resolve issues in the field.
```release-note
The CNI plugin now logs at info level by default, this makes it much easier to diagnose IPAM related issues, for example.
```
=> Log at info by default.

pkg/k8s/k8s.go
Doubt this ever gets hit but it's important to make sure we report errors through the proper CNI channel.
We're required to return an error to the CNI caller if something goes wrong.
```release-note
None required
```
=> Remove uses of Fatal on the main CNI plugin path.

pkg/upgrade/migrate.go
This is a small PR to provide more logging about datastore readiness during the upgrade
```release-note
None required
```
=> Add more logs to ease debugging calico upgrade

pkg/plugin/plugin.go
Fixes https://github.com/projectcalico/calico/issues/4084
```release-note
Fix bug that prevented pods from being torn down in some situations
```
=> Fix that we were returning an error when we shouldn't

go.mod, go.sum, pkg/ipamplugin/ipam_plugin.go
Requires https://github.com/projectcalico/libcalico-go/pull/1360/
```release-note
None required
```
=> Add timestamp to IPAM allocations

pkg/ipamplugin/ipam_plugin.go, tests/calico_cni_ipam_test.go
Fixes cases where if both IPv4 and IPv6 addresses are attempted to be auto assigned and one of the assignments fails, the other address is cleaned up appropriately.
Fixes https://github.com/projectcalico/cni-plugin/issues/908
```release-note
Fix an IPAM auto assignment bug that caused IP addresses to be leaked in dual stack environments when assignment partially succeeded.
```
=> Ensure that in dual stack environments, addresses are not leaked when either IPv6 or IPv4 addresses are not available

.semaphore/run-win-fv.sh, .semaphore/semaphore.yml, pkg/dataplane/windows/dataplane_windows.go
Host route on network has been programmed hence the same rule on Endpoints is not required.
```release-note
None required
```
=> Remove host route on endpoint with vxlan

pkg/dataplane/windows/dataplane_windows.go
```release-note
None required
```
=> Added encap route policy for l2bridge

pkg/dataplane/windows/dataplane_windows.go
```release-note
None required
```
=> Fix network id comparision on Windows OS 2004

.semaphore/run-win-fv.sh, .semaphore/semaphore.yml
Pick fix 9ecd3219ebbcb4749c9eea2bf75d50f3c1ab89cf
```release-note
None required
```
=> Fix winfvs not running

.semaphore/run-win-fv.sh, .semaphore/semaphore.yml
Co-authored-by: song jiang <song@tigera.io>
```release-note
None required
```
=> Fix WinFV (#1029)

.semaphore/semaphore.yml, Makefile
auto pin updates aren't supported
```release-note
None required
```
=> Build images before publishing and don't do auto pin updates

internal/pkg/utils/winpol/windows_policy.go, internal/pkg/utils/winpol/windows_policy_test.go
In HNS v2, the "ExceptionList" field is replaced by "Exceptions".
```release-note
None required
```
=> windows: Fix OutBoundNAT policies not being added to endpoint

internal/pkg/utils/winpol/windows_policy.go, internal/pkg/utils/winpol/windows_policy_test.go
Pick of #1067
```release-note
None required
```
=> [v3.19] windows: Fix OutBoundNAT policies not being added to endpoint (#1067)

go.mod, go.sum, pkg/k8s/k8s.go, tests/calico_cni_k8s_test.go
Companion to https://github.com/projectcalico/libcalico-go/pull/1422 and https://github.com/projectcalico/kube-controllers/pull/717
```release-note
None required
```
=> Set serviceaccount on new WEPs

go.mod, go.sum, pkg/k8s/k8s.go, tests/calico_cni_k8s_test.go
Cherry pick of #1076 on release-v3.19.
#1076: Set serviceaccount on new WEPs
=> Automated cherry pick of #1076: Set serviceaccount on new WEPs

win_tests/calico_cni_k8s_windows_test.go
```release-note
None required
```
=> Retry calico client retrieval on failure in windows test

win_tests/calico_cni_k8s_windows_test.go
Cherry pick of #1092 on release-v3.17.
#1092: windows: Remove assertion that fails when container creation
=> Automated cherry pick of #1092: windows: Remove assertion that fails when container creation

internal/pkg/testutils/utils_windows.go, internal/pkg/utils/network_linux.go, internal/pkg/utils/network_windows.go
There are 3 files whose license text is broken. This is just to fix them.
=> Fix apache-2 license text

Makefile
Cherry pick of #1133 on release-v3.20.
#1133: Fix release target
=> Automated cherry pick of #1133: Fix release target

Makefile
Fixes https://github.com/projectcalico/cni-plugin/issues/1100
```release-note
Include CNI plugin release v1.0.0
```
=> Update CNI plugin version to v1.0.0

pkg/dataplane/linux/dataplane_linux.go
```release-note
None required
```
=> report conflicting device when we fail to add route

.semaphore/cleanup.yml, .semaphore/run-win-fv.sh
This PR fixes the cleanup script which wasn't changed when we split up the winfv jobs to run on different container runtimes. It also ports the change to increase the winfv timeout.
```release-note
None required
```
=> Fix windows FV issues

.semaphore/cleanup.yml, .semaphore/run-win-fv.sh
Cherry pick of #1172 on release-v3.20.
#1172: Fix winfv cleanup script
=> Automated cherry pick of #1172: Fix winfv cleanup script

go.mod, go.sum, pkg/ipamplugin/ipam_plugin.go, tests/calico_cni_k8s_test.go
```release-note
None required
```
=> [allowed-use] Supply intended use on IPAM API.

Makefile
```release-note
None required
```
=> Use go build command from Makefile.commmon

Makefile
```release-note
None required
```
=> Fix boringssl check for other archs

internal/pkg/testutils/utils_windows.go, internal/pkg/utils/network_linux.go, internal/pkg/utils/winpol/windows_policy.go, pkg/dataplane/dataplane_linux.go, pkg/dataplane/dataplane_windows.go, pkg/dataplane/grpc/proto/cnibackend.pb.go, pkg/dataplane/windows/dataplane_windows.go, pkg/install/install.go, pkg/ipamplugin/ipam_plugin.go, win_tests/calico_cni_k8s_windows_test.go
```release-note
None required
```
=> Run goimports
