README.md
* rkt requires plugins to be executable.
* Trailing comma in network config file (rejected by rkt's parser).
=> Fix bugs in README.

calico_cni/calico_cni.py
The scripts in the appc/cni repo don't set it.
=> Make CNI_ARGS optional

calico_cni/calico_cni.py, calico_cni/tests/fv/test_calico_cni.py, calico_cni/tests/unit/test_cni_plugin.py
Also run FVs against inline IPAM plugin.
=> Return error as json, not dict

Makefile
Pulling means that a locally built container can't be used...
=> Don't pull the build container

ipam.py, tests/fv/test_calico_cni.py, tests/unit/test_ipam.py
IPv6 isn't enabled by default on some hosts.
We should make it a user configurable option to turn it on.
=> Don't assign IPv6 address when using calico-ipam

calico.py, calico_cni/constants.py, ipam.py, tests/fv/test_calico_cni.py, tests/unit/test_cni_plugin.py, tests/unit/test_ipam.py
@tomdee Turned out to be a bit more than 3 lines of code..
Allows the following:
```
{
"type": "calico-ipam",
"assign_ipv4": "true",
"assign_ipv6": "true"
}
```
=> Configuration for IPv4 vs IPv6 address assignment

calico.py, calico_cni/constants.py, calico_cni/policy_drivers.py, ipam.py, tests/fv/test_calico_cni.py, tests/unit/test_cni_plugin.py, tests/unit/test_ipam.py, tests/unit/test_policy_drivers.py
This is semi backwards compatible with existing deployments.  Upgrading to this version will still be able to handle pods / endpoints created with previous versions of the plugin.  However, downgrade from this commit to an earlier commit will leak endpoints. 
- Uses the pod namespace and name for the workload_id in Kubernetes.
- Use 'k8s' as the orchestrator when running under Kubernetes rather than 'cni'
- Also introduces a new policy driver which denies all incoming traffic.
TODO:
=> Changes for v1alpha1 policy API

Makefile, calico.py, calico_cni/__init__.py, ipam.py
Prints the version of the plugin.
Fixes #56 
Example:
```
gulfstream@gulfstream:~/repos/calico-cni$ ./dist/calico -v
{
"Commit": "582ff4ed9c2c3552ee82e417f35c8aab7ef00127",
"Version": "v1.0.2-dev",
"Branch": "version-flag"
}
```
For now, population of the version tag will be done manually on release.
=> Add version flag

calico.py
Avoids converting strings to/from unicode
=> Use yaml to read network config

samples/kubernetes/cloud-config/node-config-template.yaml
Fix typo which would cause those using search-and-replace to have a malformed cloud-config template
=> Fix typo in substitution variable

calico.py, calico_cni/util.py
correction of an error happenig when config file /etc/cna/net.d/10-calico.conf contains tab characters, and printing full stacktrace in log file in order to make easier to figure out where errors happen
=> "no handlers found for calico_cni", when conf file contains tab characters 

Makefile, calico.py, calico_cni/constants.py, calico_cni/policy_drivers.py, configuration.md, tests/unit/test_cni_plugin.py, tests/unit/test_policy_drivers.py
- Support kubeconfig as means of accessing / authenticating with API server.
- Read podCidr from k8s API when using host-local IPAM with `subnet: usePodCidr`
=> kubeconfig, podCidr support

samples/kubernetes/cloud-config/master-config-template.yaml, samples/kubernetes/cloud-config/node-config-template.yaml, samples/kubernetes/master/kubernetes-master.manifest, samples/kubernetes/node/kube-proxy.manifest
Now that 1.3.0 is released.
The changes to ` samples/kubernetes/cloud-config/master-config-template.yaml` include an assumption that this new content will be tagged `k8s-1.3-docs` (like the current content is tagged `k8s-1.1-docs`).
=> Switch Kubernetes version from 1.1.3 to 1.3.0

samples/kubernetes/cloud-config/master-config-template.yaml, samples/kubernetes/cloud-config/node-config-template.yaml, samples/kubernetes/master/policy-controller.manifest
@tomdee - I believe we're eventually moving these samples somewhere else, but for now these are the required changes for k8s v1.3.0 and policy.  I'd like to merge them so they are up to date and I can update the upstream k8s install guides.
=> Update Calico version, add policy-controller to samples.

samples/kubernetes/master/dns/skydns.yaml
Fixes #118 
v1.3.0 Kubernetes automatically creates the kube-system namespace, so we don't need to do it anymore.
=> Remove kube-system from skydns manifest

calico.go, glide.lock, ipam/calico-ipam.go, k8s/k8s.go, utils/utils.go
Contains a few distinct commits:
- Update to latest libcalico to pick up various fixes there.
- Use the container ifname as the endpoint ID rather than a randomly generated value.
- Compatibility with the old-style k8s_api_root variable.
=> Golang fixes

Makefile
This also makes `make test-containerized` work on mac.
=> Use -p so that etcd is accessible with Docker for Mac

Dockerfile, Makefile, k8s-install/scripts/install-cni.sh
This updates the `calico/cni` container to include functionality required for Kubernetes self-hosted installation.
Allows a Kubernetes DaemonSet to deploy the Calico CNI binaries, as well as a CNI network config file to each node in the cluster.
=> Install on Kubernetes using DaemonSet.

.gitignore, k8s-install/scripts/install-cni.sh
This (when complete) should allow us to simplify the self-hosted install configuration requirements by getting the API access details from the environment provided by the kubelet to the cni-installer Pod.
=> Allow template-style CNI network config in calico/cni container.

k8s/k8s.go
If the policy type isn't "k8s" the endpoint labels metadata never gets initialised and ends up as null in etcd. It looks like this causes some issues when felix tries to read from it. Making sure it's initialised fixes this.
Spoken to @caseydavenport and he mentioned this used to be handle in https://github.com/projectcalico/calico-cni/blob/master/k8s/k8s.go#L222 but https://github.com/projectcalico/calico-cni/commit/34577483abe1d69c410657c9a44ae11dff46bbd9#diff-b396ca928d5bd0e161acd283b56ead9fL121 made this optional and inadvertently introduced the bug.
=> Fix nil labels field getting into etcd when not using k8s policy

calico.go, glide.lock, glide.yaml, ipam/calico-ipam.go, k8s/k8s.go, utils/utils.go
Replace 'tigera/libcalico-go' by 'projectcalico/libcalico-go'.
Pin 'libcalico-go' to the following commit: https://github.com/projectcalico/libcalico-go/commit/0ddf9de2807feb4ef2953d78fab33e0bc78d2fdb
Change-Id: I3c835051b5cf781a78fd3ac26b86a952ac5ae067
=> Use new location of 'libcalico-go' repository

calico.go, calico_cni_test.go, glide.lock, glide.yaml, k8s/k8s.go, utils/utils.go
Updated glide to point to latest libcalico-go.
Also - need to update how workload endpoints are deleted.  Lib calico now deletes the workload when the last endpoint is deleted.
=> Update glide lock file and handle workload endpoint deletion correctly

ipam/calico-ipam.go
Current implementation of libcalico-go does not return any error if
no IPs were allocated. This patch fixes a crash listed in the bug
report.
There is a consideration to return an error from libcalico-go, if no
or not all requested IPs were allocated. Please see details here:
https://github.com/projectcalico/libcalico-go/issues/202
Closes #188
=> Check for number of returned IPs from IPAM

Makefile
Add a possibility to use custom 'libcalico-go' repo
location while building binaries inside container:
- bind additional directory with local copy of the
repository to '/go/src/github.com/projectcalico/libcalico-go'
folder inside Docker container;
- modify 'glide.lock', so 'libcalico-go' module is
taken from local path when binary is built within container
'repo: file:///go/src/github.com/projectcalico/libcalico-go'.
With this change it's possible to build CNI binaries and
test them in order to verify changes to the 'libcalico-go'.
Change-Id: Id8466eed7f86c4870fbba35fe6d12872678dc45e
=> Use local 'libcalico-go' for containerized build

Makefile, calico.go, glide.lock, ipam/calico-ipam.go, k8s/k8s.go, utils/network.go, utils/types.go, utils/utils.go
PR includes:
- Add some missing copyright statements.
- Add some context logging around errors.
- Configure environment variables used by libcalico datastore driver selection.
- For Kubernetes, procedurally generate the host-side veth name.
- For Kubernetes, procedurally generate the endpoint's MAC addr.
TODO:
Relies on changes to libcalico-go and Felix which are not yet in PRs.
=> Changes to support Kubernetes datastore driver

.dockerignore, .gitignore, Dockerfile, Makefile, k8s-install/scripts/install-cni.sh
Added host-local, loopback, and flannel CNI binaries, primarily to get Calico hosted deployment working with Hyperkube installs (e.g. CoreOS-k8s)
=> Adding CNI binaries

Makefile
Check was always hitting the exit 1 causing it to fail
=> Fix version marker checks for make release

k8s-install/scripts/install-cni.sh
Allows a user put two directories in the self-hosted manifest, and we'll install to whichever ones are writeable.
This makes the manifest more portable across multiple clusters where the directory might be read-only on some OSes
=> Support multiple dirs for install script

Dockerfile.build, Makefile, calico_cni_ipam_test.go, calico_cni_test.go, test_utils/utils.go
Simplify the build by not relying on the calicoctl binary anymore
And simplify the tests by using libcalico-go for assertions
=> Builds/Tests: Remove calicoctl and etcdctl

.dockerignore, Dockerfile, k8s-install/scripts/calico.conf.default, k8s-install/scripts/install-cni.sh
=> Supply a default CNI config in the calico/cni container.

.gitignore, Dockerfile.build, Makefile
- For vendoring
- For static checks
- For build binaries (and get a nice speedup from package cache)
- For tests
=> Makefile: Use calico/go-build

k8s-install/scripts/install-cni.sh
The `cp -n` flag does not exist in BusyBox.  Switched to using a manual
file check and copy if it does not exist.
fixes #261
=> Fix cp command in install-cni.sh

k8s-install/scripts/install-cni.sh
Stop failing fast - we expect some of the commands to fail sometimes. 
Not sure if this if the right fix long term, but this was a recent change so I'd like to revert it while we work out what to do longer term.
=> Don't fail fast for install-cni.sh

calico_cni_k8s_test.go, k8s/k8s.go
Part of issue #258 
-------------------
```
cni.projectcalico.org/ipAddrsNoIpam: "[\"10.0.0.1\"]"
```
If specified, this annotation ignores all other IPAM settings and will be stored in the Calico WorkloadEndpoint without calling any IPAM plugin, no questions asked.  This allows non-CNI things to be the source of truth for IPAM.
--------------------
=> Support Pod /32 IP request via k8s annotation (ipAddrsNoIpam)

calico.go, calico_cni_ipam_test.go, calico_cni_k8s_test.go, calico_cni_test.go, ipam/calico-ipam.go, test_utils/utils.go
Fixes #287 
This PR enables the CNI plugin to gracefully "Delete" a container that it it never "Setup". It does this by not erroring out if the resources it was called against do not exist, be it resources in the etcd datastore, or devices in the namespace it was given.
This resolves a condition that has popped up in K8s 1.6 where Kubernetes seems to lock a container in "ContainerCreating" status when Calico errors a CNI teardown request. This request was errored because Calico was never given a Create request.
This PR should also help scenarios in the future where Calico may have only half-completed a SetUp request or was called to teardown  a dirty environment.
WIP. Please don't review yet, will clean up tomorrow a.m.
=> Don't error if things don't exist

Makefile
Tested with a kubernetes 1.6 cluster kicked up with kubeadm.
Confirmed that updated flannel now handles teardowns correctly for pods it didn't setup.
=> Bundle newer CNI binaries

Makefile, calico.go, calico_cni_ipam_test.go, calico_cni_k8s_test.go, calico_cni_test.go, contrib/test_scripts/netconf/calico-go-with-host-local.json, contrib/test_scripts/netconf/calico-python-with-host-local.json, contrib/test_scripts/netconf/ptp-with-host-local.json, glide.lock, glide.yaml, ipam/calico-ipam.go, k8s/k8s.go, test_utils/utils.go, utils/network.go, utils/types.go, utils/utils.go
```bash
vagrant@vagrant:~/go/src/github.com/projectcalico/cni-plugin$ CNI_COMMAND=VERSION ./dist/calico < conf
{"cniVersion":"0.3.0","supportedVersions":["0.1.0","0.2.0","0.3.0"]}
```
TODO left:
=> Upgrade CNI plugin to support CNI Spec version 0.3.1

calico_cni_k8s_test.go, calico_cni_test.go, test_utils/utils.go, utils/network.go, utils/utils.go
fixes #306 
Calico CNI relies on Felix to configure host side route(s) and sysctls for the host veth for the pod currently, with this Calico CNI should be able to do that itself.
Route programming and interface sysctl config happens during ADD, and gets destroyed with DEL as the interface gets removed, which removes routes and sysctls.
=> Add sysctl and route programming to CNI + tests

.dockerignore, Dockerfile, Makefile, k8s-install/scripts/install-cni.sh
Adds the portmap plugin from https://github.com/containernetworking/plugins/pull/1 to the cni installer.  Currently, there is no release of the portmap plugin so this PR needs to wait until there is one.
=> Add portmap plugin

k8s-install/scripts/install-cni.sh
addresses #339
Update the install-cni.sh to loop through /opt/cni/bin/* and copy only binaries that are requested in comma string as env variable INSTALL_CNI_BINARIES
Default value set to "calico,calico-ipam,flannel,loopback,host-local" to keep backward compatibility.
/cc: @yifan-gu
=> Use comma sep. string to set install binaries

calico.go, calico_cni_k8s_test.go, calico_cni_test.go, glide.lock, glide.yaml, ipam/calico-ipam.go, k8s/k8s.go, test_utils/utils.go, utils/network.go, utils/utils.go
Updating the logrus import to use the new updated user name (which is lowercased). This will prevent import errors with vendoring going forward.
Requires projectcalico/libcalico-go#484
```release-note
None required
```
=> Update the import for logrus to use lowercasing

.github/PULL_REQUEST_TEMPLATE.md
The description for PR's isn't wrapped in a comment which is inconsistent with the release notes section below, and a bit more of a pain as users have to delete that section to fill it in.
```release-note
None required
```
=> Wrap description in comment for contributors

calico_cni_k8s_test.go, calico_cni_test.go, test_utils/utils.go
Instead, call .Path() on the netns object, which is returned anyways
```release-note
None required
```
=> Remove references to 'netnspath'

Dockerfile, k8s-install/scripts/calico.conf.default, k8s-install/scripts/install-cni.sh
These changes give the user the possibility to change calico's log level.
The log level can be changed by launching the container with the `LOG_LEVEL` environment variable containing the desired level.
This commit affects the calico.conf.default template to add a placeholder for the log level. It changes the install-cni.sh script and add the sed command to add the log level.
Finally it also provides a default value for the log-level as an env variable in the Dockerfile.
```release-note
#367 - Added configurable log level: Changes default behavior of the container by setting the log level to warn by default. To override this you can set it to info by launching the container with as environment variable: `LOG_LEVEL` to `info` (or whatever other valid level you want)
```
=> Added dynamic log level

Dockerfile
=> change maintainer to label

ipam/calico-ipam.go
Fixes projectcalico/calico#826
It looks as though we were still using the deprecated `hostname` from the CNI payload, and not `nodename` which was causing issues assigning affine blocks if you need to use a `NODENAME` that is different from the Nodes `os.Hostname()`.
I tested this on a vagrant cluster launching Calico with systemd to configure a `NODENAME` different than the Nodes hostname, and matched the `NODENAME` env var in the CNI config files `nodename`.  Without this fix the claimed blocks get assigned to the Nodes hostname in etcd, instead of the proper nodename.
```release-note
Calico IPAM will now respect the `nodename` variable in the CNI config. This will still check for the old value of `hostname` first if it exists, and will default to the Nodes `os.Hostname()` if neither is …
```
=> Fixing calico-ipam using hostname instead of nodename

calico_cni_k8s_test.go, calico_cni_test.go, utils/network.go
Fixes #352
CNI fails to setup network for the container/pod if the route already exists.
```release-note
Fix for a bug where CNI network setup fails if the route already existed on the host.
```
=> Make CNI resilient to an already existing route

calico_cni_k8s_test.go, k8s/k8s.go
We don't always update the ActiveInstanceID on workload endpoints when handling an ADD call.
This results in a scenario like so:
1) ADD for Pod X with container ID A
2) ADD for Pod X with container ID B
3) DEL for Pod X with container ID A
Since step 2 doesn't update the active instance ID, the workload endpoint gets deleted in step 3 even though there is an actively running container / Pod for that wep.
Fixes https://github.com/projectcalico/calico/issues/1117
```release-note
Fixed a bug where running Kubernetes Pods could end up without corresponding workload endpoints in the datastore
```
=> Always update the active instance ID

Makefile
Fixes #362 
Updated to CNI plugins release v0.6.0
Removed target for our fork of portmap in favor of using the version included in the CNI plugins
I tested this locally and ran the E2Es against it with no issues.
```release-note
None required
```
=> Updating to the latest upstream CNI plugin release

.gitignore, Makefile, glide.lock, glide.yaml, k8s-install/scripts/expected_10-calico.conf, k8s-install/scripts/install-cni.sh, k8s-install/scripts/install_cni_test.go, k8s-install/scripts/scripts_suite_test.go
Fixes #374 
Fixes #376 
I've added several tests to ensure at least basic functionality of the install-cni.sh script. I've also resolved a couple of minor bugs in the script for it not failing when it should.
I still have some minor concerns, I was unable to write a test to check that the script fails when we are unable to write the CNI bin files as we do not have `chattr` in the build container, and since we are running as root we have the capability to clobber anything otherwise, looking for suggestions here.
I am also unsure of this test:
https://github.com/projectcalico/cni-plugin/commit/5d1d18f2bd2ba1bdd0691c2e2cbd52f99b304eca#diff-2cac8d2716f994aa4216d877a9d2c84aR120
In the situation where both the primary and secondary bin dirs are not writable, it feels like we should fail, which …
=> Adding tests for install-cni.sh

k8s-install/scripts/install-cni.sh
Now that we have added `set -e` we have hit a couple errors. The option `-e`  when we checked if the TLS assests dir existed was __only__ checking that the dir existed, but not if it had any contents. When empty (which it is sometimes) the following `cp` call would fail. I've added a check to see if the dir exists and has something in it.
There is a similar fix in the sleep loop at the end checking to see if we need to update the secrets.
```release-note
None required
```
=> Fixing TLS copy error

calico_cni_k8s_test.go, glide.lock, glide.yaml, k8s/k8s.go
When using K8s policy, retrieve named ports from a K8s pod and attach
them to the WEP in the backend when doing an ADD.
With libcalico-go now having support for Named Ports they can be enabled in the CNI plugin
```release-note
None required
```
=> Retrieve named ports and add them to WEP

k8s-install/scripts/install-cni.sh
This will allow users to upgrade the calico cni config to a different name while at the same time will clean up the old config files. This change is useful in the case where we want to move to a `.conflist` extension to enable additional plugins such as `portmap` during a upgrade.
This mirrors changes in https://github.com/coreos/flannel-cni/pull/5.
```release-note
Optional environment variable `CNI_OLD_NAME` for `install-cni.sh` to clean up old configs when migrating to a different `CNI_CONF_NAME`.
```
=> Update install script to allow conf name changes

utils/network.go
This PR disables ip forwarding inside the container netns. By default it is enabled, because it's inherited from the host netns.
My use case for this is running containers that accept network traffic for analysis.
I'm running a container with Snort IDS in it. I have some iptables rules on the host that duplicate the traffic with `TEE` to the container. The container is seeing the traffic is not destined to it, and is routing it back out the container interface. This then causes martian source errors in the host, and is pointless overall.
I think there are pretty much no downsides to disabling this: Containers only have 1 interface, so only difference this can make is that incoming packets can no longer be routed out the single interface. I really can't think of a reason you'd want this. …
=> Disable IP forwarding inside the container netns.

calico.go
I believe the intention with the CNI plugin is that all workloads with the same conf.Name should have connectivity to each other, in the absence of any subsequent Policy.
In order to achieve that, the Profile needs to have LabelsToApply: {conf.Name: ""}, so that each WorkloadEndpoint inherits that label.
=> Set LabelsToApply on the CNI-created Profile

calico_cni_k8s_test.go, k8s/k8s.go
Fix that named ports weren't being copied across after merge of v2 datamodel.
Looks like it just got lost in the merge.
```release-note
None required
```
=> Fix that named ports weren't being copied across from the Pod spec.

Makefile
Pin the calico/go-build container to v0.9 to pick up go 1.9.2 and CVE fixes.
I _do_ think we should pin to particular releases of go-build to ensure build consistency and repeatability of older builds.  `calico/go-build` isn't a synonym for `calico/go-build:latest` either, this has tripped up a few people before.
```release-note
None required
```
=> Pin calico/build to v0.9 to pick up go 1.9.2 and CVE fixes.

glide.lock, glide.yaml, k8s/k8s.go
The libcalico-go behavior has been modified to return Pod-based WEPs (for KDD) even if they do not have any IPNetworks assigned.  The new requirement for it being a "Calico WEP" is not host-networked and a Node is assigned.
Minor tweaks to handle the fact that an endpoint will be returned in the list for the KDD scenario.
=> Handle libcalico-go returning non-IP'd WEPs

types/types.go, utils/utils.go
Added CNI test args to allow cni to set WEP namespace from command line. This is useful to have multiple namespaces for non k8s cluster. Currently it is used for test purpose only and subject to change without prior notice.
=> Added CNI test args to allow cni to set WEP namespace from command line.

calico.go, calico_cni_test.go, glide.lock, glide.yaml
Knock on effect of https://github.com/projectcalico/libcalico-go/pull/664
Rename EgressRules/IngressRules -> Egress/Ingress
```release-note
None required
```
=> Update libcalico-go and fix renaming of Ingress/Egress fields

glide.lock, glide.yaml
=> Automated update of libcalico-go to 83fc14937b8584e65bd6c959c0a85256a 2d31e28

calico_cni_k8s_test.go, glide.lock, glide.yaml, k8s/k8s.go
Revert to the Calico 2.x veth name construction algorithm.
```release-note
None required
```
=> Revert to old behavior of calculating veth name from pod name

.gitignore, calico.go, calico_cni_k8s_test.go, calico_cni_test.go, k8s/k8s.go, utils/network.go
Prevents us from releasing an IP that is still attached to the endpoint.
Fixes one of the problems identified under #1253
```release-note
Fix that, if the CNI plugin failed to re-network an existing endpoint, it would release the IP allocation to the pool even though it was still attached to the endpoint.
```
=> v1.x: Do not clean up IPAM allocations if endpoint already existed.

README.md
Semaphore badge link is incorrect - this fixes it.
```release-note
None required
```
=> Fix semaphore badge

k8s-install/scripts/install-cni.sh
Signed-off-by: zhangjie <zhangjie0619@yeah.net>
we can not write file in container source volume when  host selinux is not disable .
so if we did not disable selinux, when cni_install container started, i will occurred following errors:
```
Wrote Calico CNI binaries to /host/opt/cni/bin
CNI plugin version: 
/host/secondary-bin-dir is non-writeable, skipping
cp: can't create '/host/opt/cni/bin/calico': Permission denied
cp: can't create '/host/opt/cni/bin/calico-ipam': Permission denied
cp: can't create '/host/opt/cni/bin/flannel': File exists
cp: can't create '/host/opt/cni/bin/host-local': File exists
cp: can't create '/host/opt/cni/bin/loopback': File exists
cp: can't create '/host/opt/cni/bin/portmap': Permission denied
/install-cni.sh: line 83: /host/opt/cni/bin/calico: not found …
```
=> Copy File Error, Please check whether disabled selinux on your host

.gitignore, calico.go, calico_cni_k8s_test.go, calico_cni_test.go, ipam/calico-ipam.go, k8s/k8s.go, testutils/utils.go, utils/network.go
Prevents us from releasing an IP that is still attached to the endpoint.
Fixes one of the problems identified under https://github.com/projectcalico/calico/issues/1253
Forward-port of #418 to master.
```release-note
Fix that, if the CNI plugin failed to re-network an existing endpoint, it would release the IP allocation to the pool even though it was still attached to the endpoint.
```
=> v3: Fix ipam inconsistency

calico_cni_test.go, utils/network.go
Backport of the fix for 1253
Fixes https://github.com/projectcalico/calico/issues/1253
```release-note
bugfix: CNI plugin throws file exists while programming route
```
=> backport bugfix: CNI plugin throws file exists while programming route

.gitignore, Makefile, calico_cni_test.go, glide.lock, utils/network.go
Fixes part of https://github.com/projectcalico/calico/issues/1253
```release-note
bugfix: CNI plugin throws file exists while programming route
```
=> bugfix: CNI plugin throws file exists while programming container route

calico_cni_test.go, utils/network.go
- Applied changes made on v2.0-beta (Calico v3.0-beta)
- Setting the MAC address avoids issues when kernel fails to generate a
persistent MAC address
=> Set MAC on host side of veth pair

Makefile
Pass the ARCH environment variable to the test container
when running test-containerized targets.
Signed-off-by: David Wilder <wilder@us.ibm.com>
This fixes a recent test failures on ppc64le.
```release-note
None required
```
=> Pass the architecture to test containers.

calico.go, calico_cni_test.go, test_utils/utils.go, utils/utils.go
Here is a quick shot at checking the Ready flag before doing any operations.
Todo:
- Add some tests
- Maybe rework if we want to expose the ready flag through the Client interface instead of using a Get to the Backend
```release-note
None required
```
=> error out if Ready flag is not set (v1.11.x)

glide.lock, glide.yaml
Rev libcalico-go to pickup bgppeers ignore non-global peers fix.
```release-note
None required
```
=> Rev libcalico-go to pickup bgppeers ignore non-global peers fix

calico_cni_ipam_test.go, calico_cni_k8s_test.go, calico_cni_test.go, ipam/calico-ipam.go, utils/utils.go
Instead of just using the workload, we use the container network
namespace and the container ID combined to generate a unique handle to
track allocations.
Some questions before the WIP is removed:
- Should we be trimming off the path portion of the container network ns? It seems like so but I haven't done that yet.
- There was mention of separate code paths for k8s vs others, and it seems like they both lead back to `calico-ipam.go` so I feel like I've probably overlooked something in the code path for CNI
- If we trim out the path portion of the container net ns (and maybe even if not) I don't think there is any escaping that needs to be done
- Should we bother to check in `utils.GetHandleId()` for the container ID and network namespace as they are supposed to be a required part of the …
=> Changing the handle we use for IPAM

calico.go, calico_cni_test.go
The meaning that used to be attached to these labels is now with
Spec.LabelsToApply.
This is a cleanup that was requested during the review of
https://github.com/projectcalico/cni-plugin/pull/399.
=> Clean up superfluous Profile metadata labels

calico_cni_k8s_test.go, testutils/utils.go, utils/utils.go
Fix and un-pend formerly flaky test.
The test was assuming that the name of the veth inside the container was always "eth0" but the CNI plugin now honours the requested interface name for the container veth, _even though it always stores the WEP with name "eth0"_.
Tearing it down with "eth0" was silently ignored (the CNI plugin couldn't find the interface so it assumed the tear down had already been done).
```release-note
None required
```
=> Un-pend multi-container test.

calico.go, calico_cni_test.go, utils/utils.go, utils/utils_test.go
Slashes (`/`) are a valid character for Mesos labels.
This PR sanitizes slashes in Mesos labels by converting them to periods (`.`).
=> Sanitize mesos labels

k8s-install/scripts/install-cni.sh, k8s-install/scripts/install_cni_test.go
With Kubernetes v1.8.8 and v1.9.3 this change https://github.com/kubernetes/kubernetes/pull/57422 was introduced which creates hidden folders in any mounted in Secret.  This was problematic because now the check for files returned true but then attempting to copy (non-hidden) files failed.  This change has the check only return true if there are non-hidden files.
```release-note
Ignore hidden files when checking for etcd certificates to copy over when installing CNI.
```
=> Check for non-hidden cert files

k8s-install/scripts/install-cni.sh, k8s-install/scripts/install_cni_test.go
Cherry pick of changes in #472 into v3.0 series
```release-note
Ignore hidden files when checking for etcd certificates to copy over when installing CNI.
```
=> Check for non-hidden cert files (cherry-pick into v3.0)

k8s-install/scripts/install-cni.sh
Cherry pick of changes in #472 into v2.6 series, without the new tests as no tests existed here before.
Should I pull in all the changes that are needed to run those? 
```release-note
Ignore hidden files when checking for etcd certificates to copy over when installing CNI.
```
=> Check for non-hidden cert files (cherry pick into v2.6)

k8s-install/scripts/install-cni.sh
A few improvements to our install CNI script:
- Copy secrets with `-p` to retain permissions (See https://github.com/projectcalico/cni-plugin/issues/459)
- Set `calico-kubeconfig` mode to `0600` by default
- Move token + API location into calico-kubeconfig file.
```release-note
The install-cni container now maintains the original mode on certificates copied from Kubernetes secrets.
```
```release-note
The install-cni container now writes the calico-kubeconfig file with mode 600 by default. It can be configured by setting the KUBECONFIG_MODE option.
```
```release-note
The install-cni container now only writes the calico-kubeconfig file when running as a Kubernetes pod.
```
=> Improve secret copy + kubeconfig permissions 

calico.go, calico_cni_k8s_test.go, calico_cni_test.go, types/types.go, utils/utils.go
In combination with https://github.com/projectcalico/calico/pull/1722, will make it much harder to accidentally end up with mismatched node names between the two components.
Fixes https://github.com/projectcalico/calico/issues/1093
```release-note
The Calico CNI plugin by default expects the /var/lib/calico/nodename file to be created by calico/node. To disable this feature, set `nodename_file_optional: true` in your CNI network configuration.
```
=> Use the /var/lib/calico/nodename file if it exists

k8s-install/scripts/install-cni.sh
I realized with the recent CNI updates #481, that we needed this update since we can't make this change in the manifest anymore.
I created an IPv4 cluster and modified the CNI config to removed the k8s_api_root and auth_token and added them to calico-kubeconfig with this format and was still able to delete and start pods on the node.  I did this to verify that the format would work for IPv4.
```release-note
None required
```
=> Ensure kubeconfig server works for IPv6

k8s-install/scripts/install-cni.sh
- Fixes #1294
- Added trap handling for SIGTERM, SIGHUP and SIGINT
Bug Fix for #1294
- Why?
Adds signal handling as per the bug request
- Testing: Manual
```
$ kubectl delete daemonset calico-node --namespace kube-system --timeout=5s
$ kubectl delete pod calico-node-vjtw9 --grace-period=1 --namespace kube-system
$ kubectl log -f calico-node-4djtb --container install-cni --namespace kube-system
...
...
}
Created CNI config 10-calico.conflist
Done configuring CNI.  Sleep=true
SIGTERM received, simply exiting...
```
- which components are affected by this PR
Dont know but should not be impacted.
- links to issues that this PR addresses
#1294
kubectl delete ds / pod only does not give SIGTERM to the container.
These commands with timeout or grace-period only signaled the container with …
=> Handle termination signals in install-cni

calico_cni_ipam_test.go, glide.lock, glide.yaml
Bump version of libcalico-go to include patch where IP's aren't allocated from disabled pools.
Additionally, add a test (thanks @tmjd ) which tests IPAM to ensure this change works.
See https://github.com/projectcalico/libcalico-go/issues/689
```release-note
Don't allocate addresses from disabled pools
```
=> Dont allocate from disabled poools

k8s-install/scripts/install-cni.sh
- Added trap handling for SIGTERM, SIGHUP and SIGINT
Cherry pick of #482 
```release-note
Fixes a bug where the calico/cni container would ignore termination signals. @ketkulka 
```
=> cherry-pick 482: Handle termination signals in install-cni

calico_cni_k8s_test.go, glide.lock, glide.yaml, k8s/k8s.go
Pick up the profiles from `libcalico-go`. That way we pick up all profiles including ServiceAccounts.
Added a test to check for service account profiles and pushed up the pin for `libcalico-go`
=> Pick profiles from libcalico-go.

calico.go, calico_cni_test.go, types/types.go, utils/network.go
https://github.com/projectcalico/cni-plugin/pull/381 broke some users who were relying on this behavior, and we probably shouldn't have changed the default.
This PR makes IP forwarding configurable in the CNI network config.
```release-note
Add support for configuring container IP forwarding via the CNI configuration file.
```
=> Allow sysctl configuration

calico.go, calico_cni_k8s_test.go, calico_cni_test.go, k8s/k8s.go, types/types.go
Add a flag to enable/disable ipAddrsNoIpam. Disable it by default.
The flag is added to the toplevel section of the cni config, in a boolean field called `enable_ip_addrs_no_ipam`.  The CNI spec explicitly allows special fields at this level. I also considered adding a new object field called `calico_features` but wasn't sure there was a strong enough use case for that yet.
```release-note
Move ipAddrsNoIpam behind a feature flag in the CNI configuration, and disable it by default. Clusters currently using this feature will need to update their CNI configuration to continue using it when upgrading to this release.
```
=> Disable ipAddrsNoIpam by default

k8s-install/scripts/install-cni.sh
This will prevent it from terminating because `stat` returns non-zero
when called a non-existing file and also stat_output ends up being an
unbound variable.
Affected Component: install-cni container
@tmjd PTAL not sure if this needs a release note thanks!
=> BUG FIX: Make install-cni.sh check if the etcd cert file exist.

Makefile
The semaphore job depends on having calico/cni:latest after the build to tag and push to the repos. With a recent change the build only produced calico/cni:latest-amd64 causing the incorrect images to be tagged and pushed.
This change simply tags amd64 builds as `latest` (in addition to the `latest-amd64`).
```release-note
None required
```
=> Tag amd64 builds with latest for CI

k8s-install/scripts/install-cni.sh
Cherry picking #481, #483, #526, and #527 into the v3.0 branch.
```release-note
The install-cni container now maintains the original mode on certificates copied from Kubernetes secrets. (@caseydavenport)
```
```release-note
The install-cni container now writes the calico-kubeconfig file with mode 600 by default. It can be configured by setting the KUBECONFIG_MODE option. (@caseydavenport)
```
```release-note
The install-cni container now only writes the calico-kubeconfig file when running as a Kubernetes pod. (@caseydavenport)
```
```release-note
Fix etcd cert file existence check in calico/cni (@bjhaid)
```
```release-note
When ran as a pod CNI will be configured with K8s CA for tls verification.
```
=> Cherry-picking PRs 526, 527, 481, and 483 into v3.0

calico_cni_k8s_test.go, glide.lock, glide.yaml, k8s/k8s.go
Port the tracking and use of `generateName` metadata to release-v3.1
```release-note
WorkloadEndpoints now include the source Pod's GenerateName
```
=> Genname to v31

Makefile
Due to the hostPort does not work because of issue
https://github.com/containernetworking/plugins/pull/81 , it is
better to upgrade CNI to 0.7.1 to fix this, this can also improve
the portmap performance.
Fixed https://github.com/projectcalico/cni-plugin/issues/585
/cc @caseydavenport 
```release-note
Prompt CNI version to v0.7.1.
```
=> Prompt CNI version to v0.7.1.

contrib/test_scripts/netconf/calico-go-with-host-local.json, contrib/test_scripts/util.py, utils/utils.go
```release-note
Shut down CNI plugin if execution takes over 30 seconds
```
Fixes projectcalico/calico#2098
=> Exit if the plugin is taking too long

calico_cni_k8s_test.go, k8s/k8s.go
This PR adds the ability to define DNAT/floating IP for a kubernetes workload via annotation. Most of the plumbing was already in place, this adds the missing link. 
```release-note
You can now define a floating IP ( DNAT ) via container annotation `cni.projectcalico.org/floatingIPs`
```
=> Adding ability to define a floating ip for a kubernetes workload via annotation

calico_cni_k8s_test.go, k8s/k8s.go
Type of fix: new feature
This PR adds support to global Namespace IP Pool allocations.
The main idea here is to allow the cluster administrator to define and/or force the usage of a specific ippool in some Namespace
The following workflow happens:
* If the POD is the only object annotated with ipv4/ipv6 pools, this annotation is used
* If the Namespace is the only object annotated with ipv4/ipv6 pools, namespace annotation is used
* If both the POD and Namespace are annotated with ipv4/ipv6 pools, POD annotation is used
* If both are annotated, but the additional annotation ``cni.projectcalico.org/forceNSPools`` is found as 'true', then the ipv4/ipv6 pools annotation from namespace is used
* If forceNSpool is found as 'true' but no ipv4/ipv6 annotation are found in the Namespace, no …
=> [WIP] Adds support to use Namespace annotation for ippools

Dockerfile.amd64, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x
In order to run the image with [Docker No Volume plugin](https://github.com/projectatomic/docker-novolume-plugin) we removed
the VOLUME directive from the Dockerfiles. See #608
```release-note
None required
```
=> Remove VOLUME directive from Dockerfiles

calico_cni_k8s_test.go, ipam/calico-ipam.go, testutils/utils.go, utils/utils.go
Support using IP Pool names in the current namespace / pod annotations and CNI config instead of requiring the use of a CIDR explicitly. 
```release-note
Support specifying IP Pool by name in CNI config and Kubernetes annotations
```
=> Resolve IP Pool names to CIDRs in IPAM plugin

testutils/utils.go
log.Fatal stops the test short and bypasses test reporting. panic gives more logging output and also continues to run tests, simply marking the failed test as errored. 
```release-note
None required
```
=> Use panics instead of log.Fatal

utils/utils.go
When asked to release an IP for an AzureEndpoint which does not exist, simply return success.
This is modeled after how the Azure plugin handles this case: https://github.com/Azure/azure-container-networking/blob/master/cni/network/network.go#L609-L615
There is a case where the kubelet starts a pod before the CNI plugin can successfully network it. In this case, we'll get a DEL call for a container that does not have an IP assigned, and we need to return successfully.
It's expected CNI plugins will return successfully on DEL calls for things that do not exist. 
```release-note
None required
```
=> Support DEl on non-existent Azure endpoint

internal/pkg/utils/utils.go
Simple change to DetermineNodename to not evaluate all options, and instead, return when highest priority name is found.
Not needed, probably
```release-note
None required
```
=> Changing DetermineNodename to return when priority name is found

Makefile, internal/pkg/utils/network_linux.go, internal/pkg/utils/utils.go, pkg/ipamplugin/ipam_plugin.go, pkg/k8s/k8s.go, pkg/plugin/plugin.go
The new linter was complaining about all our `Fprintf` calls, since they return an error, which we ignore.  Might be missing something but I can't see a good reason not to use the logger now it's threaded through the code; I guess the Fprintf output is a bit more "crafted" but at this stage it's mixed in with a lot of log output so maybe better to be consistent and use the logger everywhere?
=> Automatic update of GO_BUILD to v0.20

internal/pkg/utils/utils.go
Apparently we don't support this in the CNI plugin!
Fixes https://github.com/projectcalico/calico/issues/2337
```release-note
CNI plugin now supports ERROR level logging
```
=> Support error level logging

glide.lock, glide.yaml
Changes include:
https://github.com/projectcalico/libcalico-go/compare/3655574dc6162df9974bbdebab072b5ee104b554...d23c790d2c91462a3eb64f8586b24b922159fd30
=> release 2.6: Update libcalico-go

glide.lock, internal/pkg/utils/utils.go, pkg/ipamplugin/ipam_plugin.go, pkg/upgrade/migrate.go, tests/calico_cni_k8s_test.go, tests/calico_cni_test.go
- adds a new binary `calico-ipam-upgrade` for migrating the data necessary to upgrade KDD-backed calico installations from using host-local IPAM to Calico IPAM
=> calico-ipam-upgrade Implementation

Makefile, internal/pkg/testutils/utils.go, internal/pkg/utils/utils.go, pkg/ipamplugin/ipam_plugin.go, tests/calico_cni_ipam_test.go, tests/calico_cni_k8s_test.go, tests/calico_cni_test.go
Make tests run in KDD mode with calico-ipam
```release-note
None required
```
=> Update makefile to test kdd as well

Makefile
Cherry pick of #713 on release-v3.6.
#713: Rev CNI version to 0.7.5
```release-note
Update to CNI plugins v0.7.5
```
=> Automated cherry pick of #713: Rev CNI version to 0.7.5

Dockerfile.amd64, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x
Bumping base image up to `debian:buster-slim` to be consistent with calico/node.
```release-note
None required
```
=> Upgrade base image up to debian:buster-slim

Dockerfile.amd64, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x
Switching image base to debian:9.8-slim (aka stretch-slim). 
The reason for the switch is that Debian stretch is the current stable LTS release.
```release-note
None required
```
=> Switching image base to debian:9.8-slim

Makefile
- New feature: adding the bandwidth cni plugin: (https://github.com/containernetworking/plugins/tree/master/plugins/meta/bandwidth) which allows it to use tc with Kubernetes e.g. https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#support-traffic-shaping without the need to manually install the bandwidth plugin.
- Update the cni plugins to `v0.8.0` since the bandwidth plugin is new
Fixes: https://github.com/projectcalico/calico/issues/797
```release-note
Update cni-plugins version to v0.8.0 and add bandwidth plugin for traffic shaping.
```
=> Add bandwidth plugin and update cni plugins to v0.8.0

pkg/upgrade/migrate.go
This is a bug fix for an issue observed when upgrading from Calico 3.5.4 to 3.7.2 (see #749).
I am currently manually testing this fix and am open to any suggestions.
The old call to `disk.New` causes creation of `/var/lib/cni/networks/var/lib/cni/networks/k8s-pod-network`. This is because supplying `""` as `dataDir` causes the default of `/var/lib/cni/networks` to be used. The `network` value of `"/var/lib/cni/networks/k8s-pod-network/"` is then concatenated to that default value.
This in turn causes the wrong directory to be locked.
```release-note
None required
```
=> Fix upgrade-ipam lockin wrong directory

internal/pkg/utils/utils.go, k8s-install/scripts/calico.conf.default, k8s-install/scripts/expected_10-calico.conf, k8s-install/scripts/expected_10-calico.conf.alternate, k8s-install/scripts/install-cni.sh, k8s-install/scripts/test-templates/calico.conf.alternate, pkg/types/types.go
Support the `etcdDiscoverySrv`/`$ETCD_DISCOVERY_SRV` option added to the configuration in https://github.com/projectcalico/libcalico-go/pull/1086/
```release-note
Adds support for the etcdDiscoverySrv option / ETCD_DISCOVERY_SRV environment variable when using the etcdv3 datastore.
```
=> Add etcd SRV discovery support

pkg/upgrade/migrate.go
This is a partial fix for https://github.com/projectcalico/cni-plugin/issues/749, q.v.
Clearly the intent of the code here is to be resilient in the case
where an IP (as indicated by a host-local file) has already been
assigned in the Calico data model; but the condition used to detect this
case was insufficient.  Here's a log excerpt that shows what the actual
error is here:
```
2019-05-27 15:31:52.774 [INFO][1] migrate.go 238: reading files from host-local IPAM data dir...
2019-05-27 15:31:52.774 [INFO][1] migrate.go 247: processing file... file="100.64.3.11"
2019-05-27 15:31:52.774 [INFO][1] migrate.go 291: assinging pod IP to Calico IPAM... file="100.64.3.11"
2019-05-27 15:31:52.774 [INFO][1] ipam.go 581: Assigning IP 100.64.3.11 to host: kworker-be-sandbox-iz2-bap004
2019-05-27 …
```
=> Handle migrating an IP that is already migrated

pkg/upgrade/migrate.go
Cherry pick of #750 on release-v3.7.
#750: Fix upgrade-ipam lockin wrong directory
```release-note
Fix locking of host-local IPAM directory on upgrade (@maxbischoff)
```
=> Automated cherry pick of #750: Fix upgrade-ipam lockin wrong directory

Makefile, hack/check-dirty.sh
Cherry pick of #790 on release-v3.9.
#790: Add assertion that CI builds do not result in dirty state
=> Automated cherry pick of #790: Add assertion that CI builds do not result in dirty state

.dockerignore, Dockerfile.amd64, Makefile
Related PR: https://github.com/projectcalico/node/pull/362
```release-note
Calico component images are now using ubi for the base image
```
=> Change base image from debian slim => ubi

pkg/ipamplugin/ipam_plugin.go
Proposed fix for https://github.com/projectcalico/calico/issues/2902
=> Add timeouts to cmdAdd() and cmdDel()

k8s-install/scripts/install-cni.sh, k8s-install/scripts/install_cni_test.go, pkg/plugin/plugin.go
Signed-off-by: Spike Curtis <spike@tigera.io>
If we can't connect to the datastore, but install the CNI config, Kubelet may start scheduling pods, which will just fail on this node.  So, before adding the CNI config, test a connection to the datastore. Once that is successful, proceed to add the CNI config.  If the datastore connection fails we retry in a loop.
```release-note
wait for successful connect to datastore before configuring kubelet with CNI plugin
```
=> Connect to datastore before installing CNI config

pkg/upgrade/migrate.go
Bug fix. 
Fixes https://github.com/projectcalico/cni-plugin/issues/821
The host-local IPAM plugin [writes the interface name](https://github.com/containernetworking/plugins/blob/ec8f6c99d030bd75337ae8bfc62fc02cdc462528/plugins/ipam/host-local/backend/disk/backend.go#L69) in the file where the container IP is stored. The calico-ipam plugin needs to parse the file during a migration or else it'll try and always fail to create a handle.
Couldn't find any tests for this code path, if any of the reviewers can point me to an example I'd be happy to contribute one as well.
- ~[ ] Documentation~
```release-note
Fix a bug when checking the containerID during an IPAM upgrade from host-local to calico-ipam
```
=> Fix containerID read during IPAM migration

Makefile
The invocation ` make tag-images-all RELEASE=true IMAGETAG=<tag>` was not tagging and pushing the image to gcr.io registries.
This PR addresses part of that: the `PUSH_IMAGES` variable needs to be defined before `Makefile.common` is included, otherwise `PUSH_IMAGES` will lose its initial default values. The second part is fixed in the common Makefile in https://github.com/projectcalico/go-build/pull/95
```release-note
None required
```
=> Fix release image push

k8s-install/scripts/install-cni.sh
Solves an issue where users are seeing that the existing executable is
busy and cannot be overridden, preventing Calico from starting. 
Reference: 
- https://unix.stackexchange.com/a/138241
- https://unix.stackexchange.com/a/188041
```release-note
Use mv to place CNI binaries instead of cp
```
=> Use mv to put binaries on host

k8s-install/scripts/install-cni.sh
Cherry pick of #849 on release-v3.13.
#849: Use mv to put binaries on host
```release-note 
Use mv to place CNI binaries instead of cp
```
=> Automated cherry pick of #849: Use mv to put binaries on host

Dockerfile.amd64
In k8s, where the env var KUBERNETES_NODE_NAME is not set on the cni
container, we instead use the output of `hostname`.
The old base image `debian:slim` had `hostname` built-in but `ubi-minimal` doesn't. This PR adds that in.
This PR also pins the base image for consistency with our other dockerfiles.
fixes #847 
```release-note
Fix missing hostname binary on ubi-minimal
```
=> Add `hostname` to the image and pin image

Dockerfile.ppc64le
Mirroring a change made in https://github.com/projectcalico/cni-plugin/commit/3b06d4e2a2862e9427b58b36143fb89f1efda059
to the powerpc Dockerfile. This solves a number of security issues reported in the ppc64le flavor of the CNI image hosted on quay
https://quay.io/repository/calico/cni/manifest/sha256:3496e150ef6b6444ba128e9414fec4644869c393dc5cfe38b28462c70b45bce1?tab=vulnerabilities&fixable=true
=> Change ppc64le base image from debian slim to UBI

Dockerfile.amd64
Cherry pick of #848 on release-v3.13.
#848: Add `hostname` to the image and pin image
```release
Fix missing hostname binary on ubi-minimal
```
=> Automated cherry pick of #848: Add `hostname` to the image and pin image

Dockerfile.ppc64le
Mirrors commit https://github.com/projectcalico/cni-plugin/commit/7070c4b96bd60ff9343aa5f81c7d2d64e81e2873 as well as changes made in master
The updated base image is required for a clean report from quay.io's security scan
https://quay.io/repository/calico/cni?tab=tags
=> Update base image to UBI in Dockerfile.ppc64le

Dockerfile.ppc64le
ubi-minimal is a multi-arch image. Need to specify the ppc64le manifest in the multi-arch base image otherwise the actual manifest used is determined by the system building the image. I think the only way to do that is by specifying the manifest by sha.
Need to pick to to release-v3.13 and release-v3.14.
Fixes #875 
```
laurence@user:~/go/src/github.com/projectcalico/cni-plugin$ manifest-tool inspect registry.access.redhat.com/ubi8/ubi-minimal:8.2-267
Name:   registry.access.redhat.com/ubi8/ubi-minimal:8.2-267 (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:326c94ab44d1472a30d47c49c2f896df687184830fc66a66de00c416885125b0
* Contains 4 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: …
```
=> Fix ppc64le Dockerfile

k8s-install/scripts/install-cni.sh
Fixes #877
Apparently echo masks the error. Can be reproduced with:
```bash
#!/usr/bin/env bash
set -e
echo "false in echo does not abort $(false)"
output=$(false)
echo "false in variable assignment does ${output}"
```
```release-note
install-cni.sh now also fails if `calico -v` doesn't work after copying the calico binary
```
=> k8s-install: install-cni.sh now aborts when calico -v doesn't succeed

pkg/plugin/plugin.go
Unlike k8s, Apache Mesos does not provide annotations, only labels.
This proposal is to use the `projectcalico.org/namespace` label value as namespace.
=> namespaces support for mesos

internal/pkg/utils/network_linux.go, internal/pkg/utils/network_windows.go, internal/pkg/utils/winpol/windows_policy.go, pkg/dataplane/windows/dataplane_windows.go, pkg/k8s/k8s.go, pkg/types/types.go
This PR
- Remove flag `windows_disable_host_subnet_nat_exclusion` so Calico `natOutGoing` has same effect on both Linux and Windows node.
- Refactor code for dealing with spurious add on Windows node.
```release-note
None required
```
=> Remove flag windows_disable_host_subnet_nat_exclusion

Makefile
The upgrade-ipam init container still runs `calico-ipam` but if you do a clean build with `make clean image` then that file doesn't get included.
After a bit of head scratching, I found that the `ut` target was copying that file into place so Semaphore's `make ci` included it in the image whereas `make image` doesn't.
Possible that we want to fix the manifest instead but thought it made sense to make the build sane if that file is meant to be included.
```release-note
None required
```
=> Fix that CNI plugin itself was only being included if make ut was run

pkg/install/install.go, pkg/install/install_test.go
For the hostname that we put into CNI config, we used to allow
KUBERNETES_NODE_NAME to override the system value, and
https://github.com/projectcalico/cni-plugin/pull/914 accidentally
changed that to NODENAME.  Here we revert that.
```release-note
None required
```
=> Revert accidental change from KUBERNETES_NODE_NAME to NODENAME

pkg/install/install.go, pkg/install/install_test.go
Cherry pick of #948 on release-v3.16.
#948: Fix installation of etcd secrets into config file
```release-note
Fix population of etcd certificates in CNI config
```
=> Automated cherry pick of #948: Fix installation of etcd secrets into config file

internal/pkg/testutils/utils_windows.go, pkg/dataplane/windows/dataplane_windows.go, win_tests/calico_cni_k8s_windows_test.go
Remove passing DNS information for creating l2bridge. This would allow calico-node to create calico network.
(cherry picked from commit 09bdb92807d5637bf67187bf329ea81df963baa7)
```release-note
None required
```
=> Create l2bridge without DNS info

internal/pkg/utils/utils.go, pkg/plugin/plugin.go, tests/calico_cni_k8s_test.go
File gets written by Felix in this PR: https://github.com/projectcalico/felix/pull/2511
```release-note
CNI plugin respects the /var/lib/calico/mtu file for picking pod MTU
```
=> Respect /var/lib/calico/mtu file

pkg/upgrade/migrate.go
Fixes https://github.com/projectcalico/calico/issues/3749 . This was causing a nil pointer exception since the BGP spec may not exist if the tunnel IP assignment fails.
```release-note
Fixes a bug that caused IPAM assignment to throw a nil pointer exception in cases where tunnel address IP assignment failed.
```
=> Fix error message in IP assignment which references the field it failed to set

pkg/install/install.go
Fixes a logical error pointed out in https://github.com/projectcalico/cni-plugin/issues/957 that changed the behavior of the `UPDATE_CNI_BINARIES` env variable. The actual fix for the above issue that relates to the symlink is fixed by https://github.com/projectcalico/cni-plugin/pull/966.
This was tested by setting the `UPDATE_CNI_BINARIES` values and making sure that the binaries were overwritten (or not depending on the value) when they were not expected to when the pods were restarted.
```release-note
Fix a bug that made the UPDATE_CNI_BINARIES environment variable not behave as expected.
```
=> Fix update CNI binary logic

Makefile
Cherry pick of #995 on release-v3.17.
#995: Fix make cd target to use correct tag for docker images
=> Automated cherry pick of #995: Fix make cd target to use correct tag for docker images

pkg/plugin/plugin.go
If we just return the error then we have to correlate problems with the CNI client's log (if there is one).  Make sure that we log our final error result into our own log.
```release-note
Ensure the CNI plugin logs out an error to its own log rather than relying on the CNI client to log out final errors.
```
=> Make sure we log out a final error from CNI ADD/DEL.

pkg/upgrade/migrate.go
Removes the faulty logic that caused the datastore getting stuck as being locked since it is possible for multiple nodes to become ready between the unlocking logic's polling interval. Now, the datastore should become locked whenever a node begins its migration. This leaves a very small possibility in very specific cases that borrowed IPs may overlap between host-local and calico-ipam assignments but these cases would be fixed the next time that the pod restarts.
Fixes https://github.com/projectcalico/cni-plugin/issues/990
Verified this case works by setting up a cluster where the `maxUnavailable` number is set to the number of nodes and seeing that IPAM migration will set datastore readiness back to `true`
```release-note
Fix a bug that prevented datastore readiness from being reset …
```
=> Fix datastore lock getting stuck during ipam migration

pkg/upgrade/migrate.go
Cherry-pick of https://github.com/projectcalico/cni-plugin/pull/1013
```release-note
Fix a bug that prevented datastore readiness from being reset during IPAM migration.
```
=> Fix ipam migration datastore lock 3.17

internal/pkg/utils/winpol/windows_policy.go, internal/pkg/utils/winpol/windows_policy_test.go, pkg/dataplane/windows/dataplane_windows.go
Revert changes made by https://github.com/projectcalico/cni-plugin/pull/1011  and add PA route for Windows endpoint.
Remove route policy for Windows endpoint instead because this breaks vxlan host to local pod access.
```release-note
None required
```
=> Remove route encap policy for endpoint

pkg/dataplane/windows/dataplane_windows.go
On Windows OS 2004, VirtualNetwork of a Calico_ep endpoint has lower case of Calico network ID. This cause errors if Calico CNI compare IDs in their original format.
```release-note
None required
```
=> Fix network id comparision for Windows OS 2004

.semaphore/semaphore.yml
Windows FV job could takes more than 36 minutes. Leave some room for queueing as well.  Sometimes WinFV job is pending on the queue but the timeout clock is still ticking.
```release-note
None required
```
=> Extend semaphore job timeout to 2 hours

Dockerfile.armv7, Makefile
- Allow to build the cni-plugin for armv7 architecture
- This is one of many PR for [armv7 support for calico](https://github.com/projectcalico/calico/issues/3583)
- Tests: built and tested locally
```release-note
None required
```
=> Add armv7 build

pkg/install/install.go
As the `calico` and `calico-ipam` are included in the container image next to the `install` binary, there is no need to copy them in the container.
It is also not necessary to have special logic to copy the `install` binary instead of the `calico` and `calico-ipam` binaries.
The resulting installation logic is easier to understand.
This pull request makes the `Install()` function easier to understand by removing unnecessary/redundant operations. It becomes easier to reason about what is happening when unnecessary operations are no longer present.
I tested the fix manually with manually build container images.
```release-note
None required
```
=> Simplify cni installation

win_tests/calico_cni_k8s_windows_test.go
Remove flakey assertion in windows FV test.
```release-note
None required
```
=> windows: Remove assertion that fails when container creation is slow

internal/pkg/utils/network_linux.go, internal/pkg/utils/network_windows.go, pkg/dataplane/windows/dataplane_windows.go, pkg/k8s/k8s.go
This PR updates EnsureVXLANTunnelAddr so it can be called from node during startup.
```release-note
None required
```
=> windows: update EnsureVXLANTunnelAddr so we can call it from node

go.mod, go.sum, pkg/dataplane/linux/dataplane_linux.go, pkg/plugin/plugin.go, pkg/types/types.go, tests/calico_cni_k8s_test.go, tests/calico_cni_test.go
Signed-off-by: chenqijun <chenqijun@corp.netease.com>
Now we use vpp + vcl to accelerate apps in containers, using xdp/afxdp to redirect packet from veth to vpp. 
vpp has more than one workers to process packet in our situation,  
only one vpp worker works when veth has one queue, it affect some performance.
It depend more recent kernel support.
```release-note
None required
```
=> create multi queue veth for xdp

Makefile
Cherry pick of #1138 on release-v3.20.
#1138: Change release repo to docker.io, add RELEASE and CONFIRM env
=> Automated cherry pick of #1138: Change release repo to docker.io, add RELEASE and CONFIRM env
